### ISSUE TITLE
Implement REST API for accessing feeds, submissions, and content.

### ISSUE THREAD

**Issue by kench** [concerto/concerto#1047]
I have not been able to find a machine-friendly method of finding content/submissions in a feed and full metadata for some content types.

Feeds/Submissions:
No REST API: http://nightly.concerto-signage.org/feeds/1/submissions?state=expired

Content:
Ok REST API: http://nightly.concerto-signage.org/content/12.json
Lacking REST API: http://nightly.concerto-signage.org/content/7072.json (Lovely @zr2d2 pic here)

Without a REST API, it'll be hard to re-syndicate this content on other mediums like Facebook canvas applications (which you wouldn't want inside the Concerto Rails app).

**Comment by bamnet** [comment]
I'm closing this issue for now.  Not because I don't want an API for Concerto, but because this bug is 8 years old and unlikely  to see traction in it's current form.

(I am _thinking_ about dusting off Concerto, as I do from time-to-time)

**Comment by ddbruce** [comment]
Absolutely crazy to get an email about this after 9.5 years
