### ISSUE TITLE
Timezone problem causing 500 on screens

### ISSUE THREAD

**Issue by hkparker** [concerto/concerto#1084]
On concerto 2.0.0 installed through apt on ubuntu 14.04, when a screen is viewed:

    ArgumentError (comparison of Fixnum with nil failed):
      app/models/screen.rb:260:in `each'
      app/models/screen.rb:260:in `max'
      app/models/screen.rb:260:in `block (2 levels) in frontend_cache_key'
      app/models/screen.rb:259:in `block in frontend_cache_key'
      app/models/screen.rb:257:in `frontend_cache_key'
      app/controllers/frontend/contents_controller.rb:46:in `index'
      app/controllers/application_controller.rb:112:in `set_time_zone'

This causes all digital signs to go black.  The relevant section of app/controllers/application_controller.rb:

      def set_time_zone(&block)
        if user_signed_in? && !current_user.time_zone.nil?
          Time.use_zone(current_user.time_zone, &block)
        else
          Time.use_zone(ConcertoConfig[:system_time_zone], &block)
        end
      end

Line 112 is between the else and end.  Were working on this issue and will update as we learn more.

**Comment by augustf** [comment]
@hkparker Are you still having this issue? Anyone else?

**Comment by zr2d2** [comment]
I'm fairly certain this is fixed
