### ISSUE TITLE
gif support

### ISSUE THREAD

**Issue by lovelesh** [concerto/concerto#1093]
I wanted to know if concerto supports gifs. I am using RasberryPi as me client machine and gifs donot run at all. But the preview in the server browser shows gifs with animations.

**Comment by xd1936** [comment]
Hoping this is still coming along! Keep up the great work

**Comment by mfrederickson** [comment]
The preview does not show the animation (when adding content), the content show does show the animation, and the new frontend (with polymer) shows the animation.  Closing.
