### ISSUE TITLE
Add content button not rendering properly in current Firefox (31)

### ISSUE THREAD

**Issue by augustf** [concerto/concerto#1094]
Chrome:
![screen shot 2014-08-05 at 8 09 54 pm](https://cloud.githubusercontent.com/assets/12512/3820788/2a53bca6-1cfe-11e4-8f4f-57d39252f3d6.png)

Firefox: 
![screen shot 2014-08-05 at 8 09 50 pm](https://cloud.githubusercontent.com/assets/12512/3820785/23a578fe-1cfe-11e4-8658-31d9dd382cd7.png)

**Comment by mfrederickson** [comment]
Different browsers just render the input type="file" button's and text differently.  People are familiar with their browsers and will recognize their "file picker button".  I don't think we should change this... it's not a easy thing to change.

**Comment by augustf** [comment]
Well it's not a matter of replacing the file picker button i don't think. It's simply that it's not rendering properly in Firefox (see the bottom of the button). It's not that way on any other website.

**Comment by mfrederickson** [comment]
It's not cutting off anymore...
![image](https://cloud.githubusercontent.com/assets/473165/10919772/0cefe668-8219-11e5-9b57-baceca2cdae1.png)
