### ISSUE TITLE
Frontend JS API Documentation / Do not use relative URLs

### ISSUE THREAD

**Issue by kench** [concerto/concerto#1095]
As discussed on tonight's Concerto G+ Hangout, there needs to be documentation for the Frontend JS code.  This is useful for those who want to embed it or create a screen independently of the Concerto frontend page.

This is to support the work on a Concerto Player Chromecast application.

**Comment by augustf** [comment]
Given the new frontend, I've moved this concern over to https://github.com/concerto/concerto-frontend/issues/14
