### ISSUE TITLE
WYSIWYG Editor for Text / Ticker

### ISSUE THREAD

**Issue by simplysoft** [concerto/concerto#1145]
We do think a simple WYSIWYG would make it much more easier to let users enter formatted Text / Ticker. Markdown is nice, but most users are more comfortable with WYSIWYG like interface. 
So we plan to extend the existing ticker content element with an editor. Before we start we would like to have some feedback from you guys what you think about all this:

- Do you think a WYSIWYG edit makes sense?
- How advanced should the editor be?
- Somebody already having experience with an WYSIWYG component that should be use?

Any other ideas / suggestions are welcome

**Comment by augustf** [comment]
On reflection, I'm not sure this is the direction we should be going in. Consider that in a typical deployment, most content (especially for ticker and text areas) is going to be coming into through automated means - RSS, API calls,etc and not user input. So a user-side WYSIWYG plugin fails to address the issue of how a content owner or moderator wants the things on their screen formatted.

**Comment by augustf** [comment]
At our 3/31 meeting, the consensus was that this could be a nice tool on the path to user content creation. We'd be well-disposed towards a plugin with WYSIWYG capabilities
