### ISSUE TITLE
Feeds stop updating if an rss feed contains no items.

### ISSUE THREAD

**Issue by duggan-cindy** [concerto/concerto#1147]
We've been having sporadic issues with a number of our rss feeds updating. Think that we've identified the issue.

Seems that if one rss feed does not currently have any content, all the rest of the feeds after that (in ascending order) just stop updating.  The suspect / problem feed can be determined by force updating the rss feed - get a 500 error.

We are using Concerto 2.1.1.  Also SimpleRSS  0.6.

Not sure if that is an issue in the more current version - but we can't do an upgrade in the middle of the semester.

Thanks for reviewing.
Cindy

**Comment by mfrederickson** [comment]
Fixing this in the concerto-simple-rss plugin.  Found an empty feed (at this point in time) https://511ride.alaska.gov/rss2?type=incident

@augustf can you move this issue to the concerto-simple-rss repo or should I just refer to this one in my fix?

**Comment by mfrederickson** [comment]
fixed in https://github.com/concerto/concerto-simple-rss/commit/b904a6eb6391231f34dd66e7e84d4702cada3d8b
