### ISSUE TITLE
Screen preview and field tooltips in screens#show view are not rendering correctly in mobile browsers.

### ISSUE THREAD

**Issue by kench** [concerto/concerto#1151]
I'm working on a Concerto side-project to help promote the discoverability of screens and screen content using placards placed next to the screen.  It relies on the screens#show view and while I was testing the user flow for it, I discovered that the tooltips are not rendered in the center and that the screen preview is not correctly scaled (it scales along the X-axis to fit the screen, but the Y-axis is not scaled to fit accordingly).

https://carousel.dropbox.com/photos/cc/mNumcCJUIRFlFqk

https://carousel.dropbox.com/photos/cc/upGgeQ3GOq3DyPZ

https://carousel.dropbox.com/photos/cc/z5YwiXgRVzwjFTV

Proposed Fix:
- Render tooltips that they do not overflow on smartphones.
- Scale the screen preview accordingly.

**Comment by mfrederickson** [comment]
Above pictures in dropbox are no longer available. See screen below.  by "tooltips" I think he means the pop-up field manage panel.
![image](https://user-images.githubusercontent.com/473165/65802591-98cca280-e128-11e9-84bf-eb629a6d1fee.png)

**Comment by mfrederickson** [comment]
I'm going to shelve this and open another ticket for making concerto mobile friendly.
