### ISSUE TITLE
Devise 3.4.x upgrade breaks on Travis.

### ISSUE THREAD

**Issue by augustf** [concerto/concerto#1156]
Upgrading Devise to 3.4.x requires that a secret_key config setting be defined in Devise. In a normal deployment, this can be solved by setting it to ConcertoConfig[:secret_token]. In Travis, however, the Devise initializer (even when placed after the secret token initializer) fails to find a ConcertoConfig table.

My sense is that Travis is not running the initializers in the usual order or is somehow preloading them, but it's hard to say.

**Comment by mfrederickson** [comment]
It does look like that table does not exist when running under the test environment the first time.  When I run tests manually, locally, the first time it bombs with a no secret key base, the second time it works fine because the table exists.  Since the test db is recreated each iteration, why not allow it to set it and not store it to the table if the table doesn't exist yet?

**Comment by augustf** [comment]
But I guess what I'm not following is why (since table creating is just about the first initializer) it doesnt exist yet. And you'll find that in many of the initializers, we have to kludge that issue with the config table not existing. I've yet to find out why.

**Comment by mfrederickson** [comment]
Because of this:  https://github.com/concerto/concerto/blob/master/config/initializers/01-db_create_load_or_migrate.rb#L6

**Comment by mfrederickson** [comment]
When I comment that out, testing works fine the first time.

**Comment by augustf** [comment]
Ahh yes-I'd forgotten about that other little kludge. I believe we did that because Travis doesn't like auto-creating tables.

**Comment by mfrederickson** [comment]
Does it still?  That was 2 years ago (#280).  Maybe we could detect Travis also on that line? http://stackoverflow.com/questions/12983137/how-do-detect-if-travis-ci-or-not

**Comment by augustf** [comment]
I have no idea. That article suggests its in an environment variable. Testing anything like this is always a bit weird b/c we can't replicate that unique environment. I've no idea if any code we'd write was working until Travis perhaps failed on it.

**Comment by zr2d2** [comment]
If you submit the change as a pr, you can find it if Travis likes it
