### ISSUE TITLE
Last group leader should not be able to leave the group

### ISSUE THREAD

**Issue by simplysoft** [concerto/concerto#1167]
At the moment it is possible. We think it should be not possible, but we think this is debatable.

What is prevented at the moment is that the last leader cant demote to a regular member, so to be consistent it should also not be possible to delete its membership

**Comment by zr2d2** [comment]
I agree. The goal is to make sure a group always has a leader

**Comment by augustf** [comment]
I'm not seeing this in my latest working copy, so I'm assuming it's resolved.

**Comment by augustf** [comment]
Unfortunately, despite a solid attempt at this in 64afd4c0445be0bd7142d1d194e4bccec7812251 , it failed miserably in the Travis test environment. This seems due primarily to a complex maze of tests about when a membership may be deleted from a group.

In particular, at least two tests depend on this method (https://github.com/concerto/concerto/blob/master/app/models/group.rb#L68) in the groups model that serves no other purpose than making the tests work.

If anyone wants to take a stab at making this happen, the test failure log can be found at https://travis-ci.org/concerto/concerto/jobs/49517339 . But you'll want to do a branch and pull on Github as the tests may not fail in all local environments.

**Comment by simplysoft** [comment]
I think this could be better solved by adding appropriate cancan rules instead of doing in manually. We will see if we can give it a try sometime soon

**Comment by augustf** [comment]
That's an interesting idea. If this could be done in CanCan dynamically without doing anything evil, I'd be all for it. Either way though, some tests may need to be scrapped or heavily modified.

**Comment by mfrederickson** [comment]
So are we also saying that the last leader cannot be demoted to a regular member?

**Comment by augustf** [comment]
Well as was said in the original ticket, the whole thing is a bit debatable. For most groups, this isn't really a problem since the global admin can always step in. But there may be cases where this behavior is just not desirable. But overall, as long as Concerto's last global admin can't be removed, there's no chance of putting the application into some unusable state.
