### ISSUE TITLE
Error when trying to upgrade concerto.. rake aborted! Timeout::Error: execution expired

### ISSUE THREAD

**Issue by robp2175** [concerto/concerto#1175]
Rake keeps aborting everytime I attempt to upgrade concerto

<pre># Install default configuration:
cp $(i18n-tasks gem-path)/templates/config/i18n-tasks.yml config/
# Add an RSpec for missing and unused keys:
cp $(i18n-tasks gem-path)/templates/rspec/i18n_spec.rb spec/
rake aborted!
Timeout::Error: execution expired

Tasks: TOP => environment
(See full trace by running task with --trace)
dpkg: error processing package concerto-full (--configure):
</pre>

**Comment by augustf** [comment]
This looks to be an error with the i18n-tasks gem, but since the package installs in production mode and i18n-tasks is a development-only gem, I'm not sure how this is coming up. @simplysoft may have some ideas.

**Comment by simplysoft** [comment]
If I remember correctly those messages about i18n are installation instruction that are displayed after the gem is installed. So I think the Timeout::Error did happen after the i18n-tasks gem

But @augustf is right that the i18n-tasks gem shouldn't be installed on production. It might be issue with the automatic bundle install at https://github.com/concerto/concerto/blob/master/config/boot.rb#L49, the current config https://github.com/concerto/concerto/blob/master/config/concerto.yml#L5 does not look like the development gems are excluded. Adding ``` --without development test```to the bundle_install_options should solve at least the problem that i18n-tasks is installed.

@robp2175 Did you ever try to run bundle install manually? 
The timeout might be a problem with rubygems.org, at least we did experience sometimes really slow responses that could cause timeouts. But such timeouts are rather temporary, if it still does not work, then its probably a more persistent problem

**Comment by augustf** [comment]
@robp2175 Are you still experiencing this issue?
