### ISSUE TITLE
Moving time field in screen template breaks things

### ISSUE THREAD

**Issue by snoop168** [concerto/concerto#1181]
I setup a new template. Setup new screen to use the new template. Didn't like the position of fields so modified slightly. After moving them the time field no longer worked. It was in the preview image in the complete wrong location. The screen where you can choose the subscriptions showed the time field as a "Text" field and it was no longer showing the time. I had to completely delete the field and re-add it and it worked. The time field seemed to be the only one with any issue.

**Comment by mfrederickson** [comment]
I moved the time position/field in an existing template and it continued to work properly.

I then created a new template from scratch and added a time field and it also worked fine.  I moved the time field and it still worked fine.  I am unable to reproduce this problem.

**Comment by augustf** [comment]
@snoop168 Are you still having this issue? Anyone else?

**Comment by mfrederickson** [comment]
FWIW As designed, time *is* reflected as a "TEXT FIELD" type on that screen on a base install, as you can see in the manage fields screenshot below:
![image](https://cloud.githubusercontent.com/assets/473165/6907499/1d3ab0c0-d6e3-11e4-9a06-c13fb5e6b695.png)
