### ISSUE TITLE
List available plugins on plugin page

### ISSUE THREAD

**Issue by augustf** [concerto/concerto#1183]
The plugin page, rather than simply offering a text field to enter a gem name, should read the list of available non-core plugins from https://github.com/concerto-addons via the Github API (being careful not to go over their insanely low API call limits) so users can easily browse/install the plugins we have available.

**Comment by mfrederickson** [comment]
What about third party plugins though?  Like the concerto_manykinds which isn't really a concerto org or noncore one?

**Comment by augustf** [comment]
Well, I've played with doing a search for concerto_* via the Rubygems API, but the results have been mixed. Obviously, these will only be suggestions, and the user can really install whatever they want via the form. But the problem this addresses is the user not knowing what's available.

That said, I think it may be reasonable to let anyone who wants to contribute a plugin into concerto-addons and go from there.

**Comment by mfrederickson** [comment]
Oh.  Sounds good.  Should I submit the manykinds to the addons repo?

**Comment by augustf** [comment]
Yeah-you should have no problem just transferring them over. Just confine anything you put in it to valid Concerto 2 plugins.
