### ISSUE TITLE
Frontend templates limited to one field of a given type

### ISSUE THREAD

**Issue by augustf** [concerto/concerto#1185]
We've received a comment on the mailing list to the effect that templates now only support one field of any given content type. Can anyone confirm this?

**Comment by BustyLoli-Chan** [comment]
Can confirm. Currently trying to create multiple text feeds for weather, twitter feed updates and track backs. Highlighting over any text field individually shows they all have the same subscriptions, and going to manage any of their subscriptions shows all text fields highlighted. Adding and removing feeds applies to every text field. Please advise.

**Comment by augustf** [comment]
This turns out to be something of an oversight on our part. While a “template maker” was initially intended, the process has remained rather manual. Manual, in fact, to the point that there’s no user interface exposed for creating new fields. It can be a bit confusing, but there is a “kind” called Graphic and a “field” called Graphic - which is essentially an instance of that. In our next build, you’ll find a link to create new fields on the template#edit page.

**Comment by mfrederickson** [comment]
When I manage an existing field (such as Time or Ticker) it comes up as "Graphic" as the default kind.

**Comment by mfrederickson** [comment]
`translation missing: en.field_deleted` when deleting a field.

**Comment by mfrederickson** [comment]
If you delete a field that is still referenced by a position, the template preview will no longer work-- it give a 500 return code (and hence a broken image).
![image](https://cloud.githubusercontent.com/assets/473165/6336569/f6da90de-bb4f-11e4-9208-1fe74f13dafd.png)

```
NoMethodError in TemplatesController#preview
undefined method `name' for nil:NilClass

Extracted source (around line #111):
        if !hide_text
          dw = ConcertoImageMagick.draw_text(dw,:stroke_color => "white", :fill_color => "white", :opacity => 1, :width => width, :height => height, :left => position.left, :right => position.right, :top => position.top, :bottom => position.bottom, :field_name => position.field.name)
        end
      end
      ConcertoImageMagick.draw_image(dw,image)

Application Trace | Framework Trace | Full Trace
app/models/template.rb:111:in `block in preview_image'
```

**Comment by augustf** [comment]
In addition to these fixes, I'm thinking of adding a message that these panels are not for users who aren't deeply experienced with Concerto's internals. Blowing away fields (and now positions in a cascading way) can quickly render an installation broken.
