### ISSUE TITLE
Auto-Delete Expired Content

### ISSUE THREAD

**Issue by xd1936** [concerto/concerto#1186]
It would be great if there were some way to have uploaded content that has been expired for x days to auto-delete, as per some option the Concerto's global settings. This would help keep the database small in size and optimized, as well as keep feeds with frequently-updated content small in total count.

![example](http://i.imgur.com/qVFrL2n.png)

**Comment by augustf** [comment]
I've modified an existing task we have to perform a delete of just expired content. But with Concerto being in part a system for aggregating content (and not just a transient display channel), it's not a feature we're likely to implement for general usage. You can easily invoke it either manually or periodically via cron with bundle exec rake content:purge_expired_content.
