### ISSUE TITLE
Adding background image in template editor creates more background fields

### ISSUE THREAD

**Issue by BustyLoli-Chan** [concerto/concerto#1187]
Selecting and adding a background image in the template editor initially just added a background image. Now every time I select a new image for a background and update the template there is an additional field to select a background/css. Also initially the background didn't actually update, I can't tell if there are several overlapping backgrounds sitting in this template inflating overall template size or anything either.

**Comment by mfrederickson** [comment]
Duplication of file upload buttons (one for each media entry) was confirmed when investigating #1195.
