### ISSUE TITLE
Users should see "Edit Content" button for their own submitted content

### ISSUE THREAD

**Issue by leoherzog** [concerto/concerto#1189]
If a leader of a group wants to resubmit content to a feed after it has expired, the only way to do so is to upload the content again. There should be an "edit content" button on a user's own uploads.

**Comment by augustf** [comment]
If you click on the content submission in the expired content list, on the left you'll see a Content Resubmission area. I believe that's what you're looking for.
![screen shot 2015-02-26 at 1 57 55 pm](https://cloud.githubusercontent.com/assets/12512/6399322/9f75c940-bdbf-11e4-8a33-6ef7f3f4621c.png)
