### ISSUE TITLE
Failed to upgrade from 2.2.3 to 2.2.7

### ISSUE THREAD

**Issue by robp2175** [concerto/concerto#1190]
I, [2015-03-13T08:44:24.805790 #12969]  INFO -- : Writing /usr/share/concerto/public/assets/ph/ph-e22f1f173795053fbf236f00250475bf.png
rake aborted!
Sprockets::FileNotFound: couldn't find file 'recurring_select'
  (in /usr/share/concerto/app/assets/javascripts/concerto_content_scheduling/application.js:13)

Tasks: TOP => assets:precompile
(See full trace by running task with --trace)
dpkg: error processing package concerto-full (--configure):
 subprocess installed post-installation script returned error exit status 1
Errors were encountered while processing:
 concerto-full
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by augustf** [comment]
This appears to be an error with the content scheduling assets - which is a non-core plugin. I've opened a bug in that repository.
