### ISSUE TITLE
Resubmit Content Issues

### ISSUE THREAD

**Issue by khanh** [concerto/concerto#1194]
1. Once a piece of content has expired, you can see a subheader that says "Resubmit Content" and a button that says "details". It's not clear to me that will allow me to resubmit content. It should be call to action.

2. Once that button is clicked, it opens up a modal, with an updated timeline, but the button to submit the modal, while works, looks greyed out / disabled / not congruent with the rest of the application.

3. The only situation in which i am able to resubmit content is if I am a site-wide admin. I can certainly understand if a feed owner cannot resubmit since that would resubmit it to all submitted feeds. But the user who originally submitted the piece of content should be allowed to do so.

**Comment by xd1936** [comment]
I am experiencing these three issues as well. Because #3 is an actual
software bug, this should be marked as such.

**Comment by gbprz** [comment]
To add onto this, I just noticed that after clicking on 'details' to resubmit a specific piece of content, the 'set specific times' setting doesn't toggle the necessary fields.

**Comment by mfrederickson** [comment]
The "set specific times" does seem to be working, but it is showing up behind the popped up form.
![image](https://cloud.githubusercontent.com/assets/473165/10701022/0c5df0ea-796e-11e5-9ded-267f4ed16d30.png)
