### ISSUE TITLE
Unable to change template background image

### ISSUE THREAD

**Issue by augustf** [concerto/concerto#1195]
On behalf of r6bikemonkey@gmail.com:

Currently I've set up a few templates and now want to change the background image of those templates which seemed straightforward enough. The problem is each time I attempt to upload a new background image through the gui then I get an error 500. I've also noticed that I'm not able to change the owner of the template and looking through the database entries for the templates all the owner_ids and owner_types are set to null.

Has anyone else experienced this? I've tried looking for where the background images are uploaded to the server so that I could check permissions however I'm unable to find them.

**Comment by mfrederickson** [comment]
FWIW - I installed the concerto-full package and I am able to change the background image of the BlueSwoosh without a problem.  I was able to upload a custom template package and change it's background image without problems also.  Though I do get the increasing number of file upload buttons (one per media entry-- see #1187).  And the last four columns of the template table do appear to stay null... original_width, original_height, owner_id, and owner_type.
