### ISSUE TITLE
Explore CircleCI for continuous deployment of master to a test instance

### ISSUE THREAD

**Issue by kench** [concerto/concerto#1196]
Continuous deployment (or [continuous delivery](http://en.wikipedia.org/wiki/Continuous_delivery)) is used to automate the deployment of code that is checked into source control.  I think that it would be extremely valuable to the team if we adopted using CircleCI (or another tool - I'm excited about [AWS CodePipeline](http://aws.amazon.com/codepipeline/), but it's not available yet) to help automatically deploy Concerto changes to a test instance as soon as they happen.

I understand @bamnet had some hand-written tooling to help with nightly.concerto-signage.org, but using one of these tools helps provide visibility into deployments for any team member.

**Comment by augustf** [comment]
A CI tool that actually deploys Concerto somewhere (say to be used as a demo) rather than just annoying me with its gestalt environment sounds like a definite step up.

**Comment by kench** [comment]
Ok. I did a deep dive into this.

In the past, we've used Heroku's free tier to host a test instance of Concerto, but it quickly became unmanageable due to its limitations.  Their paid options aren't cost-effective or performant ([example](http://blog.doordash.com/post/115409532041/migrating-from-heroku-to-aws-using-docker)).

CircleCI + AWS CodeDeploy seems like a workable solution for the time being, but I need admin permissions on the concerto repo to set it up.

Our usage of Travis won't change for pull requests since they provide very helpful visual feedback on whether or not a pull request is good/bad.

Open Questions:
1. Who is going to pay for this?  Setting up a good test environment does cost $.  You have speed, quality, and price.  Pick two.
2. Who is willing to be the secondary owner of this continuous deployment infrastructure in case I get hit by a bus?

**Comment by augustf** [comment]
I think the best resolution to this is to get back on the demo instance bandwagon. I'm currently hosting the live demo on a server in my basement, but long-term, we should go back to using an instance on the concerto-signage server which @bamnet kindly hosts. I know he's doing some reconstruction of that now, so I imagine a fresh demo instance will be forthcoming.
