### ISSUE TITLE
Travis no longer notifying on build failures

### ISSUE THREAD

**Issue by augustf** [concerto/concerto#1211]
With the latest batch of build failures, I've asked around to see if anyone has gotten an email notification as we have in the past, and no one has. The settings on Travis are not illuminating in this respect. Anyone have any idea what's going on?

**Comment by zr2d2** [comment]
notifications are set in [travis.yaml](https://github.com/concerto/concerto/blob/master/.travis.yml)

**Comment by augustf** [comment]
Our travis.yml would appear to conform to the guidelines in http://docs.travis-ci.com/user/notifications/ , but notifications are either not being sent, or being picked up by a Google Groups spam filter.

**Comment by zr2d2** [comment]
dare I ask, is it announcing into the IRC channel?

**Comment by augustf** [comment]
@mfrederickson Any chance your change in https://github.com/concerto/concerto/commit/3e1e4a4066b839e368fefc58c60cb658a82317ca may remedy this issue?

**Comment by mfrederickson** [comment]
I have no idea.  I just implemented what they said based on their message since it looked like we could move to their new infrastructure and it looked like they wanted us to-- and indeed the tests did run faster, as advertised.  

I'd have to look into this some more...

**Comment by mfrederickson** [comment]
It looks like the notifications are set up to only go out when the status changes.  So if it is continually failing addition emails won't go out. But what I don't know is if this applies to the repo or just the current commit... http://docs.travis-ci.com/user/notifications/

I suppose you could change it to always temporarily and see if you get them then...

**Comment by mfrederickson** [comment]
I wonder if the extra white space I inserted caused a problem with the yml structure?

**Comment by augustf** [comment]
No-this bug far predates the change you made in this commit.

**Comment by mfrederickson** [comment]
Just found out that notifications are being sent-- I added myself to the list (and have since reverted it back to normal).  But apparently they are not visible in the googlegroup-- could be some kind of filter maybe like @augustf mentioned... but I cannot look into that...

**Comment by mfrederickson** [comment]
Or perhaps someone needs to add the concerto-dev email to their settings?

> The most common cause for not receiving build notifications, beyond not having a user account on Travis CI, is the use of an email address that’s not registered and verified on GitHub. See above on how to change the email address to one that’s registered or make sure to add the email address used in this repository to your verified email addresses on GitHub.

**Comment by zr2d2** [comment]
This is because our google group is [set](https://groups.google.com/forum/#!aboutgroup/concerto-dev) so that only members can post, and [this](https://github.com/travis-ci/travis-ci/issues/2513) issue suggests you can't send travis notifications to a google group
