### ISSUE TITLE
YouTube Videos Can No Longer Be Submitted to Feed

### ISSUE THREAD

**Issue by leoherzog** [concerto/concerto#1214]
The YouTube Data API that Concerto uses is no longer supported.

![screenshot](http://i.imgur.com/aXoHZFa.png)

Check out [youtube.com/devicesupport](https://youtube.com/devicesupport) for more info.

**Comment by augustf** [comment]
This is actually a function of the remote video plugin, so I've refiled this ticket there: https://github.com/concerto/concerto-remote-video/issues/26
