### ISSUE TITLE
Add the Ability to Set Resubmission Schedule

### ISSUE THREAD

**Issue by xd1936** [concerto/concerto#1215]
It would be awesome if, when adding new content, we had the ability to set recurring automatic resubmission upon expiration.

e.g. `Show this slide every day from 8:00am to 11:00am`, or `Show this video every month on the 30th`

I realize this isn't trivial to add support for, but Google Calendar's UI handles this really well.

![GCal Scheduler](http://i.imgur.com/UcJGdgO.png)

**Comment by mfrederickson** [comment]
@xd1936 isn't what you want already accomplished in https://github.com/concerto-addons/concerto_content_scheduling?

**Comment by zr2d2** [comment]
Hi Leo,

There's a [Concerto Content Scheduling](https://github.com/concerto-addons/concerto_content_scheduling) plugin which you might find suites your needs

**Comment by zr2d2** [comment]
which @mfrederickson has already pointed out

**Comment by xd1936** [comment]
Awesome, I'll take a look. Thanks!
