### ISSUE TITLE
Update Installation Instructions

### ISSUE THREAD

**Issue by mikldt** [concerto/concerto#1219]
https://github.com/concerto/concerto/wiki/Installing-Concerto-2

The installation instructions need a once-over. A couple things appear at first glance:

* The VirtualBox Image download link appears to be to an old version. Should we just point folks at the index and let them choose? Or is there an "evergreen" link?
* New Gemfile behavior is non-obvious for the "from source" installation procedure, where it is necessary to run "bundle install" before you can run the rails server. We should document the "without" options that are now necessary here and possibly also in the Gemfile.
* No list of supported Operating Systems (at least for installation from source, where it is not as obvious as for other methods).

**Comment by augustf** [comment]
I've made some changes to address the above. But I'll leave this open pending another fresh read of the guide as well as an update to the add_repo.sh script.
