### ISSUE TITLE
Screen preview js 404 on frontend fields contents

### ISSUE THREAD

**Issue by inghamn** [concerto/concerto#1222]
We're using version 2.2.7

The javascript for requesting  /frontend/1/fields/1/contents/1 on a screen display is prepending an extra path prefix.

We have concert installed at http://host/concerto
Most everything works as expected, however, images in feed content are not displaying.  The browser is 404ing on the request.  The request for the feed images has an additional prefix added to it.

So the request is being made for 
http://host/concerto/concerto/frontend/3/fields/1/contents/16
instead of 
http://host/concerto/frontend/3/fields/1/contents/16

The images do, in fact load at
http://host/concerto/frontend/3/fields/1/contents/16

**Comment by augustf** [comment]
It would appear to met that your sub-URI configuration is wrong. Rails can be a bit odd about that sort of arrangement as it expects to have a hostname to itself. It may be that you have both Rails and your webserver adding the sub-URI. While I'm not sure what toolchain you're using, I would recommend looking at some suggestions from the folks who make Passenger on the topic: https://www.phusionpassenger.com/library/deploy/apache/deploy/ruby/#deploying-an-app-to-a-sub-uri

Incidentally, we'll be releasing Concerto 2.3 imminently and won't be taking tickets for 2.2.x frontend issues after that.
