### ISSUE TITLE
How do you update all of the bundled gems?

### ISSUE THREAD

**Issue by xd1936** [concerto/concerto#1225]
We are trying to update Concerto's plugins, and the web ui plugin update buttons are not working. How do we update the gems in `/usr/share/concerto/vendor/bundle/ruby/1.9.1/gems/`?

**Comment by augustf** [comment]
There's no button in the web UI to update all the gems-only each plugin. To update all the gems you would issue the bundle update command on the command line. We would like to hear more from folks who are having trouble with the plugin update button though.
