### ISSUE TITLE
gem only searches locally for new plugins

### ISSUE THREAD

**Issue by mfrederickson** [concerto/concerto#1227]
On a new ubuntu 14.04.3 server vm, I installed the debian package concerto-full and then tried to add the  concerto_content_scheduling plugin and it kept saying that it was not a valid rubygem.  So I tried the same gem search the code uses and it was only searching locally.  When I added the `--remote` option to the gem search command it found it.  

Should we add this option in the code ?concerto/concerto/blob/master/app/models/concerto_plugin.rb#L229

**Comment by augustf** [comment]
I had tried adding the --remote option myself, but it didn't seem to do much. But if that's working for you, I'm all for adding it.
