### ISSUE TITLE
Pages can be read and listed by non-users

### ISSUE THREAD

**Issue by augustf** [concerto/concerto#1228]
Despite this line in ability.rb (https://github.com/concerto/concerto/blob/master/app/models/ability.rb#L99), it would seem that anyone can visit the list of pages and pages themselves. I'm not entirely sure why this is the case, except to say we've done something wrong in ability.rb.

**Comment by mfrederickson** [comment]
I believe it is because of this line https://github.com/concerto/concerto/blob/master/app/models/ability.rb#L7 which creates a new user (not persisted) for anonymous/unauthenticated users.

**Comment by mfrederickson** [comment]
So just add ` if user.persisted?` to the end of your line 99.

**Comment by mfrederickson** [comment]
What is the purpose of Pages anyway?  Is seems to only exist on the admin menu. The comment in ability says that pages created by admins can be seen by users (but the app doesn't seem to make it visible to non-admins, and there is no user_id field on the pages table to enforce what can be seen/edited).

**Comment by zr2d2** [comment]
@mfrederickson, Pages are the built-in help pages. I believe the idea is they can be seen by any logged-in user. Currently they can be edited by any authenticated user, as well

**Comment by mfrederickson** [comment]
When I looked at the code and tried via the app, only admin could see them.
