### ISSUE TITLE
Update fontawesome-webfont

### ISSUE THREAD

**Issue by augustf** [concerto/concerto#1229]
I'm not sure what version it is or how it was created, but the fontawesome-webfont files in app/assets/fonts seem to be out of date. They include things like icon-question (that's our notation for the question icon), but lack ones like icon-question-circle. Does anyone know if these are Concerto specific or how they might be updated/generated?

**Comment by mfrederickson** [comment]
We should clean it up and use gem 'font-awesome-sass'.
