### ISSUE TITLE
blank frontend

### ISSUE THREAD

**Issue by snoop168** [concerto/concerto#1230]
Frontend just comes up with a blank background with the X placeholder (missing image). If I right click the X placeholder and go to properties it looks almost like the back end code is not placing the correct URL into the page. See second image. 
![blank](https://cloud.githubusercontent.com/assets/2731594/9414251/fe0393f0-4804-11e5-9bff-d130fca44bae.png)
![blank2](https://cloud.githubusercontent.com/assets/2731594/9414252/fe04001a-4804-11e5-9637-76145df561ff.png)

**Comment by augustf** [comment]
@snoop168 Is this in the current master branch of Concerto (that is, the code using the new frontend gem)? With the release of 2.3, we're closing out any tickets using the deprecated frontend code.

**Comment by snoop168** [comment]
Was the latest git clone done on the day I posted the ticket...


Sent from my Verizon Wireless 4G LTE smartphone

-------- Original message --------

**Comment by gbprz** [comment]
It seems like this was running on the Polymer 0.5 code base that had a few issues in certain browsers. Might be worth trying to run the latest 0.0.6 concerto_frontend gem that is updated to Polymer 1.0 and see if you are still having problems.

**Comment by augustf** [comment]
@snoop168 You'll find the latest frontend stuff in the current master branch if you'd like to test it out.

**Comment by snoop168** [comment]
@augustf I think I am in the master branch, and I just did a `git pull` of concerto. Does that automatically make me use the new frontend? If so then it still seems to be an issue. It works in chrome but not IE.

**Comment by gbprz** [comment]
Are you still getting the same issue with the path not resolving? From the original screenshot, I noticed you're using the frontend plugin that uses Polymer 0.5. I would check your Gemfile.lock and make sure you are using the latest frontend gem (version 0.0.6). We migrated to Polymer 1.0 in this update and hopefully it will work much better. Let me know if you continue to have any issues with IE.
