### ISSUE TITLE
Allow rotation of image submissions

### ISSUE THREAD

**Issue by augustf** [concerto/concerto#1231]
It would be nice to offer users the chance to rotate their image submissions using RMagick/ImageMagick (https://rmagick.github.io/image3.html#rotate). We could have buttons to allow 90 degree rotations in either direction that would alter the preview accordingly.

**Comment by mfrederickson** [comment]
Why not automatically orient it? https://rmagick.github.io/image1.html#auto_orient_bang

**Comment by augustf** [comment]
Well I know that some particular images will have that EXIF data, but if it has that, why would it be oriented incorrectly in the first place?

**Comment by mfrederickson** [comment]
Um... Because the auto_orient method was never called to reorient it based on the exif info...

But you're right some may not have it-- maybe both would be appropriate.

**Comment by augustf** [comment]
Yeah- I certainly dont think using auto-orient is a bad idea. I just dont have a notion of how widespread that sort of EXIF info is.
