### ISSUE TITLE
problem with ScreenTimeZone migration?

### ISSUE THREAD

**Issue by mfrederickson** [concerto/concerto#1236]
I pulled the latest in dev, tried to migrate the db, had problems so then tried a reset and have the following problem.

```
mfrederickson@artemis2:~/projects/concerto$ rake db:reset
== 20150821230410 ScreenTimeZone: migrating ===================================
-- rename_column(:screens, :locale, :time_zone)
db/development.sqlite3 already exists
db/test.sqlite3 already exists
db/development.sqlite3 already exists
db/test.sqlite3 already exists
db/development.sqlite3 already exists
db/test.sqlite3 already exists
You have 1 pending migration:
  20150821230410 ScreenTimeZone
Run `rake db:migrate` to update your database then try again.
```
Running `rake db:migrate` reports problems also...

**Comment by augustf** [comment]
If you're using it, you may want to disable automatic migrating in config/concerto.yml -- it may be that the migration and automigration are colliding. Other than that, I'm not sure why a simple rename migration would fail - I'm pretty sure SQLite supports renames.

**Comment by mfrederickson** [comment]
Bingo.  Thanks.
