### ISSUE TITLE
worker service

### ISSUE THREAD

**Issue by snoop168** [concerto/concerto#1241]
Trying to install the worker service on a new install. Is that concerto-init.d file available somewhere to download. Not seeing it in the master branch, i thought it was there in the past.

**Comment by mfrederickson** [comment]
I think maybe it got changed into two different systemd scripts in the scripts folder.

**Comment by augustf** [comment]
With the latest Debian system on systemd, we've moved to providing those scripts by default. However, anyone can generate a startup script for their OS with foreman - http://ddollar.github.io/foreman/
