### ISSUE TITLE
Destroy actions not showing flash notices

### ISSUE THREAD

**Issue by augustf** [concerto/concerto#1245]
Despite posting flash notices, none of our destroy actions show a flash notice. Not sure if the syntax with respond_with is off.

**Comment by mfrederickson** [comment]
It would be helpful to have a specific instance noted here.  Was it users, feeds, screens,  content, plugins...?

**Comment by augustf** [comment]
All of them, as far as I know.

**Comment by mikldt** [comment]
These controllers (and the others) seem to lack any code to set the flash notice in the destroy action. A good example of setting the flash notice is in [screens#create](https://github.com/concerto/concerto/blob/master/app/controllers/screens_controller.rb#L48):

```ruby
    flash[:notice] = t(:screen_updated)
```

For each controller, we will need to add such a line to be run upon successful deletion, and of course create the corresponding translation.
