### ISSUE TITLE
Profile Concerto performance with rack mini profiler

### ISSUE THREAD

**Issue by augustf** [concerto/concerto#1247]
Rack Mini profiler should prove very useful at tracking down long-running queries, slow page loads, and other performance issues - https://github.com/MiniProfiler/rack-mini-profiler

**Comment by augustf** [comment]
Oddly, I'm unable to get the profiler to start with Concerto. I can only assume it's colliding with other JS that we're using or some such thing.

**Comment by mfrederickson** [comment]
The rack mini profiler works now.
