### ISSUE TITLE
Concerto - createItemBank function not found

### ISSUE THREAD

**Issue by didierforever** [concerto/concerto#1253]
I am trying to make an adaptive test but it is giving an error by saying that the function "createItemBank" is not found. Do i need to install catR in concerto? If not, then how to fight the problem?

**Comment by augustf** [comment]
Sorry, I'm unable to draw a connection between the adaptive tests and the R programming language you're discussing and Concerto, the digital signage system. I believe you have the wrong project. If I'm mistaken, and you're doing something rather interesting involving digital signage and graphics/statistics, feel free to re-open this.
