### ISSUE TITLE
how to use check-boxes in a concerto exam?

### ISSUE THREAD

**Issue by didierforever** [concerto/concerto#1256]
I am trying to develop an exam having multiple answers to a multiple choice question.
but i am having a problem while getting the answer from the "checkbox".
for eg - 
if my answer is only A, and the test taker checks the answer A, B, C, and D, it would still mark the answer as correct.
if my answer is A, B and the test taker checks the answer A, B, it marks the answer as wrong.

i have noticed that the concerto is taking only the 1st correct marked option as the input for "checkbox".

i have named all my check-boxes as "checkbox" having values "A", "B", "C", "D".
Can someone please help.

**Comment by didierforever** [comment]
hello, can you please help with this query before closing it off.

**Comment by augustf** [comment]
I'm sorry, but you have the wrong project. This is the Concerto digital signage project. Like your last query, I'm unable to draw any connection with our project.
