### ISSUE TITLE
Updating template background doesn't change background image on template currently in use

### ISSUE THREAD

**Issue by PikaChokeMe** [concerto/concerto#1257]
I have a template that is currently running on one of our screens. When I edit this template and attempt to change its background, it's background image appears to update in the template, but does not update on the actual screen that is using the template. 

Is this a bug within concerto, or is there a different way to change the background of an in use screen?

**Comment by mfrederickson** [comment]
If you are using the latest version of concerto, v 2.3.0, then there is already a ticket for this issue here https://github.com/concerto/concerto-frontend/issues/50.  In the mean time, if you refresh the screen manually then the template change should be reflected.

**Comment by augustf** [comment]
Closing in favor of concerto/concerto-frontend#50
