### ISSUE TITLE
it is not possible to find content that has been removed from all the feeds

### ISSUE THREAD

**Issue by SteloNLD** [concerto/concerto#1262]
it is not possible to find content that has been removed from all the feeds,
possible solution: Inactive content Summary Table

**Comment by mfrederickson** [comment]
@SteloNLD you can see all of your content when you click on your username in the upper right, even the unsubscribed content.  Is this sufficient?

**Comment by SteloNLD** [comment]
@mfrederickson for now it is but the problem remains!

Expecting people to remove stale content is something unrealistic,
There's also the problem of people leaving your organization without cleaning up their mess.

Just keep this in mind ;)

**Comment by mfrederickson** [comment]
@SteloNLD I'm not sure what you mean by "expecting people to remove stale content".  Did you know that there is an automatic job that runs that purges expired content?
https://github.com/concerto/concerto/blob/master/lib/tasks/content.rake
