### ISSUE TITLE
Adding text/ticker fails with unrecognized content type

### ISSUE THREAD

**Issue by augustf** [concerto/concerto#1263]
When I go to add text of the ticker type, the message "Unrecognized content type" appears in the preview and content submission fails with a 400 error.

**Comment by mfrederickson** [comment]
This is fixed in one of my PRs

**Comment by mfrederickson** [comment]
https://github.com/concerto/concerto/commit/0a0b35f936ea7b333dd43ee0eb3eb66755f50ce9

**Comment by augustf** [comment]
Got it. Thanks!
