### ISSUE TITLE
dates overwritten with defaults when editing content

### ISSUE THREAD

**Issue by mfrederickson** [concerto/concerto#1266]
Instead of hardcoding the value for the date field in the partial https://github.com/concerto/concerto/blob/master/app/views/contents/form_elements/_dates.html.erb#L8, it should use the actual value from the model (and perhaps default the value there for new records).

**Comment by augustf** [comment]
I actually have no idea what we can do for this one. Punting...

**Comment by mfrederickson** [comment]
@gbprz didn't you fix this?  If so, can we close it?

**Comment by gbprz** [comment]
Yeah, as long as it's working as intended everything should be all set.
