### ISSUE TITLE
Graphic path in frontend broken when deployed to sub-URI

### ISSUE THREAD

**Issue by mikldt** [concerto/concerto#1283]
I'm running the latest Concerto on Passenger under Nginx. I have the app deployed to /concerto with `passenger_base_uri /concerto`, so that the app is served at https://example.com/concerto. I'm getting 404s on all images requested by the frontend (meaning the frontend text is visible, but the background is black and content images don't appear).

It appears that the base URI is getting applied twice in the URL sent from concerto to the frontend for Graphics and template images. A request to https://example.com/concerto/frontend/4/fields/1/contents.json results in the "/concerto" prefix being applied twice, as follows:

``` json
    [{"id":10,"name":"Moon","duration":12,"type":"Graphic","render_details":{"path":"/concerto/concerto/frontend/4/fields/1/contents/10"}}]
```

I believe this double prefixing is originating in the Graphic model. The relative_url_root is applied manually, but I believe the URL helper inserts it as well:

``` ruby
  def render_details
    {path: "#{Rails.application.config.relative_url_root}#{url_helpers.frontend_screen_field_content_path(self.screen, self.field, self)}"}
  end
```

Is there some use case where putting this in there was necessary? Or is it possible that this was from a previous rails version or untested? If we can work out that the relative_url_root will be applied in the url helper in all possible use cases where its needed, then we should get rid of the `Rails.application.config.relative_url_root`.

**Comment by mfrederickson** [comment]
Looks like that's my mistake.  At one point I had a suburi set up and that was required.  I'll remove that and test it both ways...
