### ISSUE TITLE
Slides repeating up to 6 times in a row.

### ISSUE THREAD

**Issue by robp2175** [concerto/concerto#1284]
I have about 15-20 slides right now in multiple feeds. While the feeds are cycling often the same slides will repeat a couple of times. Sometimes the same slide will repeat as much as six times before moving to another slide. This is with a brand new server with the newest version. Something is clearly wrong and any help to alleviate this problem is greatly appreciated.

**Comment by SteloNLD** [comment]
I have the same issue, slides wil randomly repeat for a random amount, i am using RPi2-Win10(IoT)

**Comment by robp2175** [comment]
I'm using the newest virtual machine created by the concerto team.






On Fri, Nov 20, 2015 at 2:40 PM -0800, "Sten Lootens" <notifications@github.com<mailto:notifications@github.com>> wrote:


I have the same issue, slides wil randomly repeat for a random amount, i am using RPi2-Win10(IoT)

-

**Comment by mfrederickson** [comment]
BaseShuffler works as expected, but I am seeing the same problem in the frontend screen...

**Comment by mfrederickson** [comment]
The problem appears to be that the session is getting lost and therefore the array of ids of content are not getting persisted across contents.json requests-- at least when I test with polyserve for the frontend and concerto with the backend using a slightly tweaked demo.html page.  I'll check a pure concerto environment next...

Evidently iron-ajax will not send the session_id cookie (required by rails regardless of the session store) unless `with-credentials="true"` but CORS doesn't allow the with-credentials with an Allow-Origin of *.

**Comment by mfrederickson** [comment]
I'm not sure what was causing me to see the problem in the first place-- could have been needing to run `rake tmp:clear` to clear out the cache session store?  But anyway, this appears to be working fine as is.  No changes were needed to the frontend code.  However, I do think #1287 should be applied for completeness.

@robp2175 or @SteloNLD can you give me any more information--- do you have any other concerto plugins other than the default ones?  Have you set the field-config for the specific screen for the specific field for shuffler to BaseShuffle?  What session store type are you using?  Is there a proxy server being used?

**Comment by mfrederickson** [comment]
@robp2175 and @SteloNLD an even more pertinent question is do you have multiple players accessing the same screen?  These multiple consumers of the same (screen/field) queue could make it look out of order.

**Comment by robp2175** [comment]
Yes, I do have multiple players access the same screen. However, I have always done this with previous versions and never had this problem.

**Comment by mfrederickson** [comment]
Thinking about it some more, that probably should matter since each session is unique per client....

**Comment by SteloNLD** [comment]
'Session Store' is set to 'Cookie Store', Rpi2-Win10IoT and Win8.1-Firefox  players seem to both have this issue, i installed Concerto on Ubuntu using Concerto-Full., if you need anything ask me ;)

**Comment by mfrederickson** [comment]
@SteloNLD can you run this following (using your own URL of course) and cycle through them to see if they are coming back in the correct order?  Change 4 to your screen number, and 1 to whichever field is showing the repeat content.

`http://concerto/frontend/4/fields/1/contents.json`

**Comment by SteloNLD** [comment]
http://{my super secret server}/frontend/1/fields/1/contents.json gives content back randomly and sometimes the same content in my opinion.

i have 3 iFrame slides (name them 1, 2, 3) and i am getting these in the following order, 21231212311332213121 when opening the URL with EDGE on Windows 10

My Raspberry Pi player uses the Windows10-IoT Operating system, the app i created uses a webbrowser-control which is based on EDGE or Internet Explorer, this player seems  to work better than my Windows 8.1 Desktop with Firefox player so am going to do the test here to.

**Comment by robp2175** [comment]
@mfrederickson What is considered the "correct" order? My slides are coming back in this order. 7, 8, 29, 32, 193, 422, 425, 446, 19, 20, 21, 11, 12, 13, 14, 15, 16, 443 then they cycle back through in the exact order. The same behavior is seen using Chrome and Firefox.

**Comment by robp2175** [comment]
@mfrederickson My apologies for not answering some questions you asked earlier. Here are the answers. 

Do you have any other concerto plugins other than the default ones? 
Yes, I am using the Concerto Content Scheduling Plugin

Have you set the field-config for the specific screen for the specific field for shuffler to BaseShuffle?
Yes, after seeing this problem I setup a field config (shuffler, BaseShuffle), but this has little effect. 

What session store type are you using? 
Cookie Store

Is there a proxy server being used?
No

**Comment by mfrederickson** [comment]
@robp2175 good point-- the correct order would be a non-repeating, somewhat ascending (per feed/subscription) order-- which it looks like yours is.  So it would appear that your screen is displaying non-random/non-(immediately)-repetitive content, is that correct?

**Comment by mfrederickson** [comment]
@SteloNLD I'd like to see if there are session problems.  Can you add the following line, verbatim, to your _contents_controller.rb_ file which is located in your _/usr/share/concerto/app/controllers/frontend_ directory.  It should be added after the line that reads `count = 1` in the index method (for me, it was around line 29).

```
Rails.logger.info("session_key: #{session_key}, value: #{session[session_key]}")
```

This will add a log entry each time content is requested by any of your screens.  It wont actually start using the changed file until you restart your webserver with the following command. 

```
sudo service apache2 restart
```

Let it run for a few minutes.  Then run the following in your _/usr/share/concerto/log_ directory, inspect the results, and if you are willing, paste it here so I can see what is going on.

```
 grep session production.log | tail -30
```

**Comment by robp2175** [comment]
@mfrederickson It may be that this problem seems to have resolved itself for me, although not sure how. When I setup a field config for BaseShuffle and that had no effect. I then also changed the transition effects to replace so that if the slides did repeat, noone would notice. Now, because of that change, it is also more difficult for me to notice :-)   Based on the test results you had us run, the slides no longer appear to be repeating for me. Very odd.

**Comment by augustf** [comment]
@mfrederickson Have the last few commits and some troubleshooting dealt with this issue?

**Comment by mfrederickson** [comment]
@augustf I was hoping to get some insight from @SteloNLD on the session, but yes, I think it has been resolved.  If he still has problems with the 2.3.2 release perhaps he can open another issue and we can dig deeper.
