### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by snoop168** [concerto/concerto#1301]
What are the best permissions for the concerto folder? I have user/group set to root:www-data
Any folders in there need to be writable by all? I realized a lot of the issues I was having was due to permission problems so for now im CHMOD 777 everything except I guess passenger does not like the log file to be 777, wanted 666 so i'm wide open right now except for the one log file at 666. Want to restrict down now to a safe level that will work.

Thanks in advance.

**Comment by augustf** [comment]
There are many different schools of thought on how you want your permissions set-up, but generally you want files with sensitive data (like database.yml) accessible to only the user that needs it and the rest of the files with just the permissions needed for them to be used or executed, as the case may be. A Rails app is generally started as the owner of the file config/environment.rb, while Rack applications are started as the owner of config.ru. That may be significant depending on which websever you're using. You may also be able to specify the user and group that you want the application started as and in which mode you'd like it started.

If you look at the concerto-debian package file (https://github.com/concerto/concerto-debian/blob/master/build-scripts/debian-common.sh#L66), you'll see the permissions we use for things, which are deemed to be pretty sensible. Some major things to avoid are files needlessly set with "execute" permissions, root ownership of anything (I use www-data:www-data usually), and of course root running any webserver-related process (possibly for the reasons mentioned above).
