### ISSUE TITLE
Set maximum font size for text fields

### ISSUE THREAD

**Issue by snoop168** [concerto/concerto#1305]
Have an RSS feed being displayed in a text field. There are 2 elements created, a `<H1>` and `<P>`. Not sure how the sizing works but often times my H1 field is gigantic. Is there any way to force a maximum size through the style on the text field for certain element types?

**Comment by mfrederickson** [comment]
In an attempt to fit the content to the size of the sign, the text is autosized based on an algorithm, and you can see here https://github.com/concerto/concerto-frontend/blob/master/concerto-behaviors.html#L45 where the minimum is 4px.  A couple lines up from that you can see that there is a field configuration that you can use to turn off autosizing.

Specifying a padding or margin that is relative to font size (using units of em's) can cause the autosizing feature to not work properly.

**Comment by snoop168** [comment]
I see the option and it does work however it doesn't really accomplish what I am trying to do. Let me ask this maybe. When data is imported from an RSS feed the application inserts some HTML into the content, namely `<h1>` tags for the title and `<p>` for the content. I am using the "articles" option in the RSS "display type". So really what I want to do is perhaps define a MAX size for both the `<h1>` and `<p>` tags. The resizer almost does too good of a job fitting stuff perfectly in the space that when content has only a few words the title especially could be read from a mile away.

**Comment by mfrederickson** [comment]
The only way that I can think of to do this is to use that config param to turn the auto sizing off, and then use a CSS stylesheet in the template.

**Comment by augustf** [comment]
I think it would be possible to allow a user to configure the maximum font size they'd want to allow in a text field. Otherwise, a field with just a few words could have its font get way out of hand.
