### ISSUE TITLE
Only half-images displaying

### ISSUE THREAD

**Issue by augustf** [concerto/concerto#1306]
For some time, we've been getting reports of images displaying in this fashion:

![image1](https://cloud.githubusercontent.com/assets/12512/11902477/2a43e464-a580-11e5-95a8-4d5f8f3178a9.JPG)

We've so far been unable to narrow it down to a core or frontend issue. In fact, reproducing it reliably is problematic, though I have a Raspberry Pi (shudder) that seems to do it consistently.

**Comment by augustf** [comment]
Tony DeLaurie from the forum suggests:
```
Remove "top: 50%" from the CSS and it should display fine:

img.concerto-graphic {
position: relative;
top: 50%;
 transform: translateY(-50%);
```

**Comment by mfrederickson** [comment]
Related reading:
http://www.w3.org/Style/Examples/007/center.en.html
Maybe we should investigate using the CSS Level 2 solution instead of the Level 3 solution?

**Comment by augustf** [comment]
@mfrederickson So are you saying this is an implementation anomaly with the centering code? Or are we using it incorrectly?

**Comment by mfrederickson** [comment]
I'm not sure... but if the centering solution (which seems to be a level 3 solution) isn't working reliably, maybe a level 2 solution would.  I'd like to know what @gbprz thinks...

**Comment by gbprz** [comment]
Although this uses flexbox (CSS3), maybe we can make use of the Polymer iron-flex-layout classes:  https://elements.polymer-project.org/guides/flex-layout. It's possible this solution will be more consistent with our choice of Polymer and give better results.  

I'm not a CSS expert, so I would need to research a CSS level 2 solution a bit more. Let me know what you think, I have a old Raspberry Pi that I can try to reproduce it on as well.
