### ISSUE TITLE
format for time

### ISSUE THREAD

**Issue by snoop168** [concerto/concerto#1309]
Is there a way to modify the format of the time that is used on the frontend displays? I was looking mainly to remote the `<br>` element from it to hopefully fit the time on one line and make its font a little taller. Is that hard coded somewhere if so can someone point me to the file?

**Comment by mfrederickson** [comment]
There is a field configuration (see the wiki) for formatting the time. If there is no time format field config then a default format is used which contains a `<br>`.  You can see the logic here:  https://github.com/concerto/concerto-frontend/blob/master/contents/concerto-client-time.html#L48

**Comment by garci66** [comment]
Sorry to revive old threads, but I noticed that the custom format string allows "escaped"  html to be added. In my case, for the field, I added the attribute "time_format"  and set it to the followig:

	`[<div class=clientTime-date>]DD/MM[</div><div class=clientTime-time>]HH:mm[</div>]`

The formatter used in javascript for the GUI takes everything between the square brackets as escaped code, thus I added additional CSS classes, but you could easily add <br>, etc..  Hope it helps!
