### ISSUE TITLE
Dropping Ruby 1.9.3 Support

### ISSUE THREAD

**Issue by gbprz** [concerto/concerto#1311]
With many of our gems requiring Ruby 2.x, the current Rails 4.2.5 migration ( #1310) is running into some strange issues with Ruby 1.9.3.

I've tried locking the versions of certain gems based on their Ruby version requirements listed on RubyGems, but I'm still getting errors. I've tried multiple versions of the Tins gem that support Ruby 1.9.3 and it seems to be giving me the most trouble. If anyone has any advice on this, I would appreciate it. Seems like there is a related open issue already: https://github.com/flori/term-ansicolor/issues/28

Also since Rails 5.0 will only work with Ruby 2.2.2+, would it be a good idea to begin dropping Ruby 1.9.3 support in the next migration to Rails 4.2.5 or should we wait until we switch to Rails 5?

**Comment by kench** [comment]
Ruby 1.9 is end-of-life:

https://en.wikipedia.org/wiki/Ruby_(programming_language)#Ruby_1.9
https://www.ruby-lang.org/en/news/2014/01/10/ruby-1-9-3-will-end-on-2015/

**Comment by augustf** [comment]
I don't believe our gem choice leaves us much room here either. Many of the key gems we use are now requiring Ruby 2.0 or greater. The limiting factor has been and remains Debian. While Jessie at least runs 2.1, Wheezy does not. But at this point, I think we'll just have to bit the bullet and move away from 1.9.x.

**Comment by zr2d2** [comment]
:+1:
