### ISSUE TITLE
Update RSS settings

### ISSUE THREAD

**Issue by snoop168** [concerto/concerto#1312]
Is it possible to modify the RSS settings, specifically the XSLT and display type after its already submitted? I am only able to locate the screen where you can change the Name and Time Frame. 

On another note, if you try and change the dates on content it doesn't actually save the new dates. Is that the same problem as #1266 ?

**Comment by mfrederickson** [comment]
No, those fields are not editable after a piece of content has been initially saved.  Perhaps for admin users they should be?

**Comment by snoop168** [comment]
Ok. I'm playing with the XSLT feature and if you dont get it right on the first shot you have to re-do it completely. Did you mean the dates cant be edited too or is that an actual issue.

**Comment by mfrederickson** [comment]
@snoop168  #1266 fixes the date problem.

**Comment by robp2175** [comment]
I know this is a really old issue ans closed, but in case someone comes upon it I thought I would share this. Host your XSLT file on a webserver (I actually host mine right on my concerto box using a different port). Then use this code, changing your url of course. Now, you only have to change the file on the server. To see the changes immediately, you will need to purge and force update the content. I hope this helps someone.

```
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
  <xsl:import href="http://concerto.domain.edu:81/weather/weather-xslt.xml"/>
</xsl:stylesheet>
```
