### ISSUE TITLE
image size warning

### ISSUE THREAD

**Issue by mfrederickson** [concerto/concerto#1313]
It would be a good idea to display the image size somewhere under the preview when adding an image, and give a warning if it is larger than a predetermined size...

**Comment by augustf** [comment]
@mfrederickson Do you have any notion of sizes where we're starting to see problems. And is this a matter of MB of size vs pixel size?

**Comment by mfrederickson** [comment]
I think it was actually pixel density/depth/resolution or whatever you want to call it that was causing problems for Matthew.  But the large MB size was also causing slow display times (sometimes the picture did not have enough time to download and display before the screen called for the next piece of content).

**Comment by mfrederickson** [comment]
Closing since  #1320 already shows the size info, and the criteria of the warning would vary too much based on hardware/network/user needs.
