### ISSUE TITLE
permissions

### ISSUE THREAD

**Issue by snoop168** [concerto/concerto#1314]
Can someone explain the different permissions a bit. I've looked through the [Authorization](https://github.com/concerto/concerto/wiki/Authorization) Wiki page but I don't think it touches on a few permissions.. I'm trying to learn what the "Screen Permissions" and "Feed Permissions" drop downs grant on the Group->Manage Members page do. Also, does "group leader" just grant "all" on both of these options and also allow the leader to approve new members into the group?

Basically, I want to allow a user to submit to a feed (automatic approval) but not be able to add new feeds. If I set the Feed Permission to All, they can do both. Any suggestions? I initially checked off the "is submittable" option without making a group but then they couldn't browse. I didnt want to use the "is viewable" option because then NON LOGGED in users would be able to browse and I didnt want this either. I only want my LOGGED IN users to be able to view the items in the feed. Maybe make the feed "is submittable" but still creating the group to grant them the view permissions only when they are logged in? I'm thinking then that the group could be set to NONE for the feed permissions because it will get its submit ability from the "is submittable" option.

Update: Tried setting the "is submittable" flag but that doesn't auto approve...

**Comment by snoop168** [comment]
also, what determines the screens permissions (as far as what feeds can be subscribed to)... Is it derived from the "Owner" of the screen. I'm sort of unique where I want my screens to sometimes span multiple feeds that may be somewhat private to the groups mainly for submission purposes but I also dont want to make the feeds "is visible" because that essentially opens the feeds up to public view on the web interface. Our screens are all in secured locations only visible by people who have access to these locations but the web interface can obviously seen by anyone on the network that has access to can figure out the url to the web interface...

**Comment by augustf** [comment]
Wow-a lot of questions here. I'll try to address some of them, but in the future, do try to use the mailing list for support inquiries.

>> I'm trying to learn what the "Screen Permissions" and "Feed Permissions" drop downs grant 
Feed and screen permissions are granted to group members to allow them control over the the two entities the group can own -- screens and feeds. For each of those, they can have operational (submission/subscriptions) control, full control, or no control.

>> does group leader allow the leader to approve new members into the group
Yes. The main perk of being a group leader is the ability to manage the members of the group and their permissions.

>> I want to allow a user to submit to a feed
Setting the group user's feed permission to "Submission" should accomplish that.

>>  I initially checked off the "is submittable" option without making a group but then they couldn't browse
The "is submittable" and "is viewable" options serve to make the feed open to viewing and/or submissions from non-members of the group.

>> then NON LOGGED in users would be able to browse and I didnt want this either
If you don't want non-authenticated users to browse your Concerto content, go to the Permissions tab under settings and turn off "Public Concerto."

>>  I also dont want to make the feeds "is visible" because that essentially opens the feeds up to public view
If your Concerto isn't public, and the same group owns the non-viewable feeds which are subscribed to by an authenticated screen, its contents won't be viewable except to group members or on the physical screen.
