### ISSUE TITLE
Update from 2.2.6 -> 2.3.2 Results in 500 Error on /settings Page

### ISSUE THREAD

**Issue by leoherzog** [concerto/concerto#1321]
Hello!

We have tried updating our Concerto server from 2.2.6 to 2.3.2 in a couple of different ways. It's running on Ubuntu 14.04 in our VM cluster.

We have tried doing an `apt-get dist-upgrade` on the server itself. We have tried creating a new server from scratch and importing the database by hand. We've tried running `rake db:migrate` at different points during the upgrade procedure.

Every time, we get this screen when we browse to or click on "Settings":

![What happens when we click on "Settings" or we browse to ourserver.com/settings](http://i.imgur.com/5iZOicR.png)

and this error in `concerto.log`:
https://gist.github.com/xd1936/5c0d18617d465b30c384

Any idea what we can do to get our 2.3.2 server upgraded and in a working state? I can't seem to find upgrade instructions anywhere in the Wiki or on the website or forum.

**Comment by augustf** [comment]
@xd1936 By the looks of the log, some of your concerto config select_value fields have been corrupted. Since there there only 2, the best thing is probably to fix them manually. mailer_protocol can be set to:

```{'Sendmail' => 'sendmail', 'SMTP' => 'smtp'}```

and session_store can be set to:

```{'Cookie Store' => 'cookie_store', 'Cache Store' => 'cache_store', 'ActiveRecord Store' => 'active_record_store'}```

**Comment by xd1936** [comment]
@augustf Thanks for the quick reply! We'll give that a shot and report back

**Comment by xd1936** [comment]
Where would I find these `concerto config select_value fields`?

**Comment by augustf** [comment]
@xd1936 These are rows located in your database. You'll want to edit your SQLite/MySQL/Postgresql database directly to add these values.

**Comment by deltaYankee88** [comment]
I needed to add a field to the table concerto_configs in database concerto_production as that field was missing from the database. After that field was added I could add the above info for the mailer_protocol and session_store. The 500 error is now gone. Than you.

**Comment by xd1936** [comment]
(@deltaYankee88 is my coworker. This solved our issue, thanks)

**Comment by xd1936** [comment]
Hey @augustf, how would those session_store and mailer_protocol changes been made if we hadn't added them by hand? Is there some script that we are supposed to run in order to update the database schema?

**Comment by augustf** [comment]
@xd1936 No, what I suggested was a manual kludge for an installation that had gotten strangely broken. This isn't really something we anticipate happening to the extent we'd write a script.

**Comment by xd1936** [comment]
@augustf Thanks for the quick reply. I ask because we are having another 500 error now, this time when we click on the "New Screen" button in the UI. Here's the error in `production.log` this time:

https://gist.github.com/xd1936/eb5af5a505ecf7a3b3fe

This server/database has been updated from ~2.0.x through a few major versions, and is currently on 2.3.2.

Thoughts? We're considering just starting over again and recreating all of our users/screens/feeds/content, since these bugs keep popping up.

**Comment by augustf** [comment]
@xd1936 This would appear to be an unrelated issue. It looks the your screen table lacks a time_zone column. This can occur after an incomplete upgrade -- which typically happen when migrations aren't run. This can happen if auto-migration is turned off in config/concerto.yml or the app isn't restarted after the code upgrade. It can usually be fixed by running bundle exec rake db:migrate.

**Comment by xd1936** [comment]
Hmm. Well, we did run `bundle exec rake db:migrate`, but we don't have anything about auto-migration in our config/concerto.yml.

Here's our contents of concerto.yml:
    automatic_bundle_installation: true
    automatic_database_installation: true
    compile_productions_assets: true
    airbrake_enabled_initially: true
    bundle_install_options: "--path vendor/bundle"

It looks like it's missing a line about auto-migration...

**Comment by augustf** [comment]
@xd1936 No - automatic database installation is what handles the automatic migration. If running db:migrate isn't getting you the time_zone column though, some upgrade must have gone horribly wrong -- leaving your database out of sync with your codebase.

**Comment by xd1936** [comment]
I guess that's what happened.

We moved into `/usr/share/concerto/config` and ran `sudo bundle exec rake db:migrate`, and still no luck.

**Comment by augustf** [comment]
@xd1936 You shouldn't run rake in the config folder - I'm not sure that will work. It should be run in the root of the application as your current user (not root). If that fails to give you a time_zone field (check this with your database-viewing tool of choice), your installation was likely upgraded in some catastrophically broken way.

**Comment by xd1936** [comment]
By "Application Root", do you mean `/usr/share/concerto`? If so, we did give that a try, and we got an error about not having permission on `schema.db`. We then added ourselves to the `www-data` group and ran it again, but still get the 500 error. Still no `time_zone` field in our database (we use Webmin to look at it). There's a `system_time_zone`, but no `time_zone`.
