### ISSUE TITLE
Edit HTML context text editor not showing

### ISSUE THREAD

**Issue by Carharttguy** [concerto/concerto#1322]
Hello

When trying to edit to edit the text of a submission, the preview is showed, but the text editor is not showing.

See screenshot, happens on FF and Chrome.

<img width="1412" alt="schermafbeelding 2016-02-19 om 18 20 19" src="https://cloud.githubusercontent.com/assets/5918262/13203096/21d9b71a-d8af-11e5-8455-21dec6debad4.png">

Thank you
Mathias

**Comment by augustf** [comment]
@Carharttguy This isn't a bug. Once a submission is approved by a moderator, it's no longer editable. This ensures the integrity of the moderation process, which would mean nothing if the submitter could edit their submission after the fact. There's a discussion already underway about making an exception for system-wide administrators, but we've not reached a resolution on that yet.

**Comment by Carharttguy** [comment]
Yes, I understand, but data integrity is either way not ensured because chances are high that a moderator has access to the DB and he/she could change the data there easily.
