### ISSUE TITLE
PDF conversion quality (again)

### ISSUE THREAD

**Issue by mfrederickson** [concerto/concerto#1324]
It seems the quality of the conversion is still not as good as it should be.  Suggest testing one of these methods instead of relying solely upon docsplit when going from PDF to JPG/PNG.  `-trim` would also benefit maximizing the content.

http://stackoverflow.com/questions/6605006/convert-pdf-to-image-with-high-resolution

For past issue regarding PDF quality see #973.

**Comment by augustf** [comment]
If we don't use docsplit for doing this, is there a general case for the convert command that will give good results? From that post, it would seem the command line passed is highly dependent on the input and output desired.

**Comment by mfrederickson** [comment]
Adding `density: 300` to the `Docsplit.extract_images` parameters in the content_converter.rb file (around line 75) helped some.  But replacing that line with the following helped more, I think.

```
          if original_filepath.end_with? ".pdf"
            Rails.logger.debug("pdftoppm -r 300 -singlefile -png #{original_filepath} /tmp/#{File.basename(original_filepath,".*")}_1")
            `pdftoppm -r 300 -singlefile -png #{original_filepath} /tmp/#{File.basename(original_filepath,".*")}_1`
          else
            Docsplit.extract_images("#{original_filepath}", density: 300, pages: 1, format: 'png', output: "/tmp")
          end
```
