### ISSUE TITLE
Revisit Shuffling Algorithm

### ISSUE THREAD

**Issue by mikldt** [concerto/concerto#1331]
The current `WeightedShuffle` algorithm makes content repetition ("B A A C") and even nearby repetition ("A B A C") possible and in some cases fairly likely, even when there is enough content that it is not necessary. This repetition, especially immediate repetition, looks like a glitch from the perspective of someone viewing a screen, which in my view takes precedence over the idea of giving each content an even probability of occurring at any given time.

V1 Concerto lessened this issue by ensuring that when multiple feeds are present, the timeline cycles through the feeds. This would help in many (though not all) situations. It certainly wouldn't hurt.

https://github.com/concerto/concerto_v1/blob/master/common/driver.php#L90

We might also want to look at how we perform the shuffling (per feed and per repetition for additional weight), and/or direct measures to prevent content repetition.

Criteria for closing this ticket: immediate content repetition should be entirely eliminated, or eliminated with conditions (e.g., minimum number of content and minimum number of feeds).

**Comment by ddbruce** [comment]
I will add that some templates have multiple graphics fields. It would be good to attempt to prevent both fields showing the same content at the same time.

**Comment by mfrederickson** [comment]
Wouldn't that depend on the subscriptions?

**Comment by augustf** [comment]
We have a ticket like this on the frontend (https://github.com/concerto/concerto-frontend/issues/38), but I've not gotten an idea as to how practical this will be.

**Comment by ddbruce** [comment]
I know that there are some vertical screens at RPI that have two graphics fields, and they both have the same feeds associated with them. It's done to have double the content at once and get closer to the normal aspect ratio of submitted content.

It always looks weird when the same content appears in both fields at the same time.
