### ISSUE TITLE
Change a subset (or all) screens to a specific template

### ISSUE THREAD

**Issue by ddbruce** [concerto/concerto#1332]
This is a feature request to be able to select a bunch of screens, change them all to one template, and be able to revert back to the previous template later.

An example that comes to mind would be a special event (e.g. Commencement weekend at RPI or Reunion/Homecoming). Concerto admins might want to easily change a bunch of screens to fit the event's theme without having to go to each screen individually.

**Comment by gbprz** [comment]
I think this could be very useful, along with some other features to speed up repetitive admin tasks. 

I started a plugin to try out the template swap idea and it seems to work well.
https://github.com/gbprz/concerto-admin-tools

A little crude, but it gets the job done:

![screenshot - 04182016 - 11 53 57 pm](https://cloud.githubusercontent.com/assets/3246274/14627284/d40012c0-05c0-11e6-8e87-7bfd9fa0d041.png)

Feel free to post any more suggestions for tasks that could be simplified.

**Comment by ddbruce** [comment]
Can the templates be easily swapped back?

**Comment by gbprz** [comment]
Nope, but now it sounds like the requested functionality would better match the concerto template scheduling plugin. https://github.com/concerto-addons/concerto_template_scheduling

Maybe if some sort of mass assignment feature was added to that plugin it would make more sense. Or we can add a database table to this plugin and store the previous template_id, but it seems like making use of an already existing plugin might be best.

**Comment by Baylink-gh** [comment]
I have suggested on the ML that it would be nice to indirect the schedule to a named list, so it could be used on more than one screen; I suspect now that the extra indirection to "select a (possibly named-group) bunch of screens, and then apply this schedule to this template against the entire group".

And if we're gonna do that indirection, that might be a good time to look at multi-tenancy, as well... :-)

**Comment by mfrederickson** [comment]
Moved to concerto_template_scheduling repo.  https://github.com/concerto-addons/concerto_template_scheduling/issues/27
