### ISSUE TITLE
Code commented out in 2012 still kicking around

### ISSUE THREAD

**Issue by augustf** [concerto/concerto#1334]
I happened to run into this gem today: https://github.com/concerto/concerto/blob/master/app/views/subscriptions/_form.html.erb#L23

Probably time for someone who know's what's up with it to clean it up.

**Comment by gbprz** [comment]
To go along with this, we should probably cleanup the previous frontend's stylesheets.

https://github.com/concerto/concerto/tree/master/app/assets/stylesheets/frontend

**Comment by zr2d2** [comment]
are we currently degrading gracefully for non-js users?
