### ISSUE TITLE
concerto-lite 2.3.3 still uses ruby 1.9.1

### ISSUE THREAD

**Issue by matthewlswanson** [concerto/concerto#1341]
Running a new install of Debian and ran sudo apt-get concerto-lite. Once the installation runs for a few minutes I get this error

/var/lib/dpkg/info/concerto-lite.postinst: 7: /var/lib/dpkg/info/concerto-lite.postinst: gem1.9.1: not found
dpkg: error processing package concerto-lite (--configure):
 subprocess installed post-installation script returned error exit status 127
Errors were encountered while processing:
 concerto-lite
E: Sub-process /usr/bin/dpkg returned an error code (1)

But installing concerto-full works so maybe this was forgotten for the latest 2.3.3 update?

**Comment by augustf** [comment]
This was a recurring issue with differences between Debian and Ubuntu Ruby versions, which was addressed some time ago. But now in resolving https://github.com/concerto/concerto-debian/issues/61, this issue should go away entirely. Concerto and its Rails dependencies can in no way support versions below Ruby 2.1, and the new Debian control file enforces that.
