### ISSUE TITLE
Airbrake upgrade from 4-5 breaking with notifier error

### ISSUE THREAD

**Issue by augustf** [concerto/concerto#1342]
Back in 117ffac82ad5de31ab77864626442956a7e97654 , we moved from Airbrake 4 to 5. When building Concerto now, I get the following error:

```
Airbrake::Error: the 'default' notifier isn't configured
vendor/bundle/ruby/2.1.0/gems/airbrake-ruby-1.0.3/lib/airbrake-ruby.rb:287:in `call_notifier'
vendor/bundle/ruby/2.1.0/gems/airbrake-ruby-1.0.3/lib/airbrake-ruby.rb:237:in `build_notice'
vendor/bundle/ruby/2.1.0/gems/airbrake-5.0.1/lib/airbrake/rake/task_ext.rb:21:in `rescue in execute'
vendor/bundle/ruby/2.1.0/gems/airbrake-5.0.1/lib/airbrake/rake/task_ext.rb:19:in `execute'
```

Moving bback to 4.1.0 mitigates this, so I'm assuming this is a regression we introduced in moving to 5.

**Comment by gbprz** [comment]
It might be worth trying airbrake 5.3.0, not sure if this is related in any way: https://github.com/airbrake/airbrake-ruby/issues/28

If this works, we can set the version in the reporting Gemfile.

**Comment by FluffyMilk** [comment]
Trying Airbrake 5.3 works, but we need to make sure that we define a project_id and a project_key in the intializers file for airbrake 13-airbrake or so. 
(currently don't have access to my concerto setup, so i can't tell you the full filename).

if we have an empty project_id and / or a project_key, Airbrake throws an error message.
The error is also thrown, if you disable the "send errors to the developers" checkbox in Concerto.

https://github.com/airbrake/airbrake/issues/546

**Comment by augustf** [comment]
https://github.com/concerto/concerto/pull/1381/commits/acdbcf1e21b6cb4edc0d6569ec5bd55141a0aa99
