### ISSUE TITLE
Online screens not displaying correctly

### ISSUE THREAD

**Issue by matthewlswanson** [concerto/concerto#1343]
I just migrated the install from Ubuntu 14.04 running 2.3.2 to Debian Jessie running 2.3.3. I did this because of future compatibility issues. Everything seems to be working EXCEPT the screens page is going bonkers. LOVE the blue to show online screens by the way. The amount of screens online and offline are changing drastically every few minutes and are switching between black and blue whilst refreshing the screens page. It is showing many of the screens that are online and working as offline.

**Comment by augustf** [comment]
Is anyone else reproducing this issue?

**Comment by augustf** [comment]
https://github.com/concerto/concerto/pull/1338
