### ISSUE TITLE
Force update on weather doesn't work

### ISSUE THREAD

**Issue by ddbruce** [concerto/concerto#1344]
http://concerto.rpi.edu/content/8590/act?action_name=manual_refresh throws the following:

![image](https://cloud.githubusercontent.com/assets/5694673/15454912/3b23a31a-2013-11e6-9298-2693782e427b.png)

**Comment by ddbruce** [comment]
Actually, it looks like an RPI-specific problem. I'll close.

**Comment by gbprz** [comment]
@ddbruce Looks like the RPI deployment needs a plugin update. It's still running the version that uses the Yahoo weather API, try out 0.3.2 instead and see if it helps. 

![screenshot - 05222016 - 12 40 43 pm](https://cloud.githubusercontent.com/assets/3246274/15455171/6b6b276c-201a-11e6-96ce-2c266fb3dc10.png)

Keep me posted on any issues that might happen during the upgrade. Also, there are some additional steps to installation including an API key for the OpenWeatherAPI and precompiling assets for the weather icons. More details here: https://github.com/concerto/concerto-weather

If it helps, I can try the upgrade myself but I don't want to intrude.

**Comment by ddbruce** [comment]
I hit the "upgrade" button and after a few minutes saw a banner saying that the update was successful. When I refresh the page, the old version is still there, and when I try to add weather content, it still throws a 500.

**Comment by gbprz** [comment]
Did you add the API key?

**Comment by gbprz** [comment]
Also seems like you will have to create new weather contents. We are making API calls with different params than before, and those are stored in the database. The old yahoo stuff won't work anymore.

**Comment by gbprz** [comment]
And if you want the weather icons, you'll need to precompile assets

**Comment by gbprz** [comment]
https://github.com/concerto/concerto-weather

**Comment by ddbruce** [comment]
I'm not really sure how to take care of any of these issues. If you have time, feel free to fix them. If not, no worries. Thanks!

**Comment by ddbruce** [comment]
![image](https://cloud.githubusercontent.com/assets/5694673/15487136/c24dcffe-2118-11e6-92cf-7372596b1f6d.png)

**Comment by gbprz** [comment]
Interesting, the restart button might not be restarting the web server and triggering the bundle update/install. I'll check it out, was on mobile so was just listing things in comments

**Comment by gbprz** [comment]
For some reason there is no edit comment feature on this app

**Comment by gbprz** [comment]
@ddbruce Just upgraded the weather plugin along with a few others including the frontend. I also pulled in the latest changes to core Concerto. Let me know if you experience any issues, hopefully you're still able to login and use all the normal features. I also created some new weather content and it seems to have worked well now.
