### ISSUE TITLE
Automatically precompile assets when installing / upgrading Concerto plugins

### ISSUE THREAD

**Issue by gbprz** [concerto/concerto#1345]
All of the code exists to run a rake task for precompiling assets:
[Helper method to invoke Rake Task](https://github.com/concerto/concerto/blob/f5cd0a1d6709f02bf6a96ce86b9d496aaeec3566/app/controllers/application_controller.rb#L133)
[Install a new Gem calls helper](https://github.com/concerto/concerto/blob/f5cd0a1d6709f02bf6a96ce86b9d496aaeec3566/app/controllers/concerto_plugins_controller.rb#L49)
[Update a Gem calls helper](https://github.com/concerto/concerto/blob/f5cd0a1d6709f02bf6a96ce86b9d496aaeec3566/app/controllers/concerto_plugins_controller.rb#L111)

But I don't think the actual rake task exists (let me know if I'm blind and can't find it), so users are left to manually precompile assets for plugins including the frontend and weather. It might save some trouble if this is added in since people run into black screens or missing weather icons often.

**Comment by augustf** [comment]
https://github.com/concerto/concerto/pull/1376
