### ISSUE TITLE
Repo/OVA/package down

### ISSUE THREAD

**Issue by k3nnyfr** [concerto/concerto#1347]
As of today everything seams to be down : 
- get.concerto-signage.org/add_repo.sh
- http://dl.concerto-signage.org/concerto_server.ova

Servers issue ?

**Comment by bamnet** [comment]
Yup, server issue.  Kept getting too many connections for Apache to handle, seems like apt-get sends a ton of connections at once.

I switched to nginx, hopefully that performs better serving these static files.
