### ISSUE TITLE
Concerto Emergency Alerts

### ISSUE THREAD

**Issue by ddbruce** [concerto/concerto#1351]
RPI had a test of the RPIAlert system today. Concerto's config was a little wonky, but we ended up getting it to work.

Some issues, however: RPI instance-aside, Emergency Alerts seems to kick in whenever there is an RSS piece of content (even without children) on the monitored feed. That is, RPI has a feed called "Emergency Alert" that takes an RSS feed from RPI Public Safety. Even if there is no active content in that RSS feed, the plugin activates. To deactivate, I had to remove the RSS feed entirely.

For reference, here's the pre-alert and during-alert RSS feeds: 

`<?xml version="1.0"?><rss version="2.0" xml:base="http://alert.rpi.edu" xmlns:dc="http://purl.org/dc/elements/1.1/">
<channel>
<title>RPIalert - alert</title>
<link>http://alert.rpi.edu</link>
<description></description>
<language>en</language>
</channel></rss>`

`<?xml version="1.0"?><rss version="2.0" xml:base="http://alert.rpi.edu" xmlns:dc="http://purl.org/dc/elements/1.1/">
<channel>
<title>RPIalert - alert</title>
<link>http://alert.rpi.edu</link>
<description></description>
<language>en</language>
   <item>
<title>RPI ALERT</title>
<description>This is test a of the RPIAlert System. No action is needed. </description>
<link>http://alert.rpi.edu</link>
   </item>
</channel></rss>`

**Comment by mfrederickson** [comment]
Are you on the latest versions of the plugin and concerto?  I thought that specific problem had been fixed.

**Comment by ddbruce** [comment]
That's a very good question. I'm working on rebuilding the entire instance as we speak to fix all the stupid issues our system has been having. I'll respond if/when there's an answer.

**Comment by ddbruce** [comment]
The issue was on our end. A previous version of the weather update used incorrect parameters for the current version, causing DynamicContent.refresh to crash. After the old weather contents were removed, everything updated correctly every 5 minutes.
