### ISSUE TITLE
RSS feed crashes with incorrect string value

### ISSUE THREAD

**Issue by ddbruce** [concerto/concerto#1353]
TechCrunch though it would be a good idea to use emojis in their headlines, leading to a crashing of DynamicContent.refresh.

Headline:
![image](https://cloud.githubusercontent.com/assets/5694673/18836489/450577e0-83ce-11e6-9333-53afbfa0d222.png)

Error message:
`Mysql2::Error: Incorrect string value: '\xF0\x9F\x8E\xB6 C...'`...

**Comment by mfrederickson** [comment]
@ddbruce is your database.yml including the utf8 encoding setting for your database?  And is your database encoding within mysql set to utf8?

**Comment by ddbruce** [comment]
@mfrederickson It was not. It was set to `latin` something or other. I changed it to `utf8_general_ci`.

**Comment by mfrederickson** [comment]
@ddbruce please reopen if you continue having problems with this.
