### ISSUE TITLE
http://dl.concerto-signage.org/ is down - redirects to namecheap parked domain page

### ISSUE THREAD

**Issue by shmergin** [concerto/concerto#1354]
As above, download links for the .ova files fails.
http://dl.concerto-signage.org/ currently redirects to a namecheap domain parking page.

**Comment by bamnet** [comment]
Yea, I'm in the process of renewing one of the domains that the CNAME for the server backing dl.concerto-signage.org.  It looks like Namecheap is pretty aggressive at installing their own nameservers.  I expect them to point back at the Amazon route53 ones soon.
