### ISSUE TITLE
Outdated Ruby, libruby, and apache2-mpm Dependencies

### ISSUE THREAD

**Issue by Loufe** [concerto/concerto#1355]
When trying to install concerto-full via apt-get I get the following errors. It's challenging to know what to do here as apache2-mpm doesn't exist anymore (nor do any upgrades). While libapache2-mpm-itk exists, I'm not sure if it's going to be fully compatable.

concerto-full : Depends: ruby2.0 but it is not installable or
                          ruby2.1 but it is not installable
                 Depends: libruby2.0 but it is not installable or
                          libruby2.1 but it is not installable
                 Depends: apache2-mpm-worker but it is not installable or
                          apache2-mpm-prefork but it is not installable

**Comment by augustf** [comment]
What version of which distribution are you trying to install this on? Our v2 package is only compatible with the stable Debian Jessie at present.

**Comment by Loufe** [comment]
Ah! It was not clear that V2 was only compatible with Debian. I set everything up on Ububuntu Server 16.04.10 so far. Should I restart with debian 8.6 then?

**Comment by augustf** [comment]
You may want to do that, yes. Concerto does work perfectly well with Ubuntu, but the developers have changed package names that depart from the Debian ones, and change their minds somewhat often about those names. It is our intention to have the package work with Ubuntu, once we get a handle on their naming changes.

**Comment by augustf** [comment]
The latest Debian package fixes some issues with Ruby versions (Debian oddly only supports up to Ruby 2.1, not 2.2) and resolves the package naming differences between Debian and Ubuntu.
