### ISSUE TITLE
librmagick-ruby package no longer a part of apt repository

### ISSUE THREAD

**Issue by Loufe** [concerto/concerto#1356]
On both debain 8.6 and Ubuntu 14.04 there exists no package in the standard repositories of apt.

**Comment by augustf** [comment]
Thanks for catching that. We'll look into this and get a new package built in the next few days.

**Comment by Loufe** [comment]
August, thanks for the quick reply. Additionally, on Debian, "gem install passenger" fails:

ERROR:  Error installing passenger:
        rack requires Ruby version >= 2.2.2.

**Comment by augustf** [comment]
@Loufe I've gone ahead and released new packages, which should account for this issue, package name differences between Debian/Ubuntu, and old packages that are no longer needed. The new VM reflects this.
