### ISSUE TITLE
Graphic upload doesn't work on Firefox 49.0.1

### ISSUE THREAD

**Issue by asquared** [concerto/concerto#1358]
On Firefox 49.0.1, when uploading a graphic, it appears that the AJAX request to do the actual upload never happens. The JavaScript executes and activates the throbber in the preview area, and no errors appear in the console, but the request appears neither in the dev tools network tab nor on the server.  Also it does not appear that either the complete or error callback is called. This was leading to the behavior described in issue #1357.

I'd troubleshoot further but at the moment I'm a bit stymied by the Rails JS minification process. 

p.s. should the complete callback really be a success callback at graphics.js.erb line 24? From the docs it appears that complete is called after success or error, no matter what happened with the request. But the code looks like it's only intended to run on a successful upload.

**Comment by asquared** [comment]
Upon further investigation this appears to be upstream in jquery.iframe-transport.js. See https://github.com/cmlenz/jquery-iframe-transport/issues/44.

**Comment by augustf** [comment]
Feedback we've gotten indicates this was not an issue in current browsers as of Oct 21: https://groups.google.com/forum/#!searchin/concerto-digital-signage/HANG%7Csort:relevance/concerto-digital-signage/DEUJgo1ouso/hF1WzIp6AgAJ
