### ISSUE TITLE
Installing using apt-get in Ubuntu 14.04

### ISSUE THREAD

**Issue by matthewbassett** [concerto/concerto#1359]
Hi,

I'm attempting to install concerto-full on ubuntu 14.04, however following the instructions I get the following error:

Gem::InstallError: cancancan requires Ruby version >= 2.0.0.
An error occurred while installing cancancan (1.13.1), and Bundler
cannot continue.
Make sure that `gem install cancancan -v '1.13.1'` succeeds before bundling.

I looked in the instructions and it says that concerto-full includes ruby 1.9, so I found it a bit weird that one of the dependencies was trying to use a newer version of ruby? I've also tried installing ruby2.0 manually, but no joy. Thanks for any help you can send our way!

**Comment by augustf** [comment]
@matthewbassett While our control file for the Debian package requires Ruby, it does not yet ensure that 2.0+ is used. If you were to install the present package, or upgrade your distribution overall, you would get the latest (which in Ubuntu should be 2.2 or 2.3). Our package presently works from our knowledge of what Debian is using for a Ruby (which tends to be criminally out of date). You can track our progress in ensuring you get Ruby 2.0+ here: https://github.com/concerto/concerto-debian/issues/61.
