### ISSUE TITLE
Table Query Error in Concerto v5

### ISSUE THREAD

**Issue by aboukhary** [concerto/concerto#1360]
I am trying to write R code to insert a row using a statement that I migrated from concerto v4. 

The error message says:

Error in (function (classes, fdef, mtable) : unable to find an inherited method for function ‘dbEscapeStrings’ for signature ‘"NULL", "character"’

This is my first time to use concerto v5 and I am not sure if installation or security were set properly. I was see any problem with my R code.

**Comment by augustf** [comment]
I believe you have the wrong software. Concerto is a Ruby on Rails application and is on version 2.
