### ISSUE TITLE
display issue

### ISSUE THREAD

**Issue by snoop168** [concerto/concerto#1361]
Having a display issue and seems to be related to a chrome update. 

![image](https://cloud.githubusercontent.com/assets/2731594/20179491/6192ca42-a724-11e6-90a1-4e140da6ea40.png)

In the developer console i see the following error over and over: 
Uncaught TypeError: Failed to execute 'animate' on 'Element': 'function (a){return a}' is not a valid value for easing(…)

Related to: https://github.com/PolymerElements/neon-animation/issues/162 ??

I definitely don't have the latest version of concerto, do you know if upgrading will resolve this issue I am having?

Chrome 53.0.2785.116 m worked fine, once my PC upgraded to 54.0.2840.99 m I began to have the issue.

**Comment by timparenti** [comment]
Started encountering the same issue on 31 October 2016, most likely after an automatic Chrome upgrade.  Other deployed units are currently fine.  Developer console shows near constant `Urgent content update`s, and the same `TypeError`s as above, even on a fresh install of Chrome 54.0.2840.99 m (64-bit) on Windows 8.1 Pro.  It appears the Concerto server we're talking to is running Concerto 2.3.1.

**Comment by timparenti** [comment]
As a workaround, I've switched the affected display to [Firefox ESR 45.5.0](https://www.mozilla.org/en-US/firefox/organizations/) with the [mKiosk 2016.10.1](https://addons.mozilla.org/en-US/firefox/addon/mkiosk/) plugin.

**Comment by augustf** [comment]
This issue should be resolved in the latest release of the frontend plugin.
