### ISSUE TITLE
updating plugins

### ISSUE THREAD

**Issue by snoop168** [concerto/concerto#1363]
I want to update my plugins. When I click "Upgrade" I get a message saying it was successful but the version number never goes up... Somehow I managed to get my Frontend plugin to say LOCKED and don't know how to fix that... 

Just to add, I ended up just manually running `sudo gem install concerto_frontend` and seemed to do the trick

**Comment by augustf** [comment]
In this context,, "locked" means that in the plugin's database entry, you've specified a particular version (see code at https://github.com/concerto/concerto/blob/master/app/views/concerto_plugins/show.html.erb#L38). If you change that entry to specify no version, the plugin should upgrade freely. If you did this with Rubygems, you'd probably want `bundle update concerto_frontend`.

**Comment by snoop168** [comment]
ok, but still seem to have an issue upgrading the plugins via the gui... I'm trying to upgrade and just get the message saying it was upgraded yet the version number doesn't increment... 

![image](https://cloud.githubusercontent.com/assets/2731594/20839699/9713eb66-b87b-11e6-9084-b4016e9366d5.png)
Do you simply hit the upgrade button or do you need to edit the plugin and set the target version first?

I think by me running the `sudo gem install concerto_frontend` I forced the gem to be updated without the GUI's knowledge... Am i correct by this assumption.. I am sorry Ruby/ROR/Passenger/Bundler/Gems are all greek to me. I'm used to PHP etc...
