### ISSUE TITLE
Broke when I tried to update

### ISSUE THREAD

**Issue by bdamron** [concerto/concerto#1366]
We were having issues with plugins not working and we were trying to update them and now the entire system is not working. We get "Web application could not be started" error. At this point I would just appreciate getting everything undone and back to where it was.

I've attached the error screen.

[Concerto error.txt](https://github.com/concerto/concerto/files/634685/Concerto.error.txt)

Thanks

**Comment by augustf** [comment]
It would appear that the web server user no longer has access to the file Gemfile-plugins. You can correct this with the chmod and/or chown commands. In general, you'll get better responses on the mailing list, though. We try to use the issue tracker for known/suspected defects in the software, not individual environment issues.
