### ISSUE TITLE
Playing with Debian 9 Stretch (Request not bug)

### ISSUE THREAD

**Issue by matthewlswanson** [concerto/concerto#1382]
Got a new install of Debian Stretch going and decided to play with getting Concerto installed on it.
Some of the package names have changed, how can I tell the Concerto install to use these new package names?

default-mysql-server
default-mysql-client
default-libmysqlclient-dev
ruby-mysql2

**Comment by mfrederickson** [comment]
I don't think you can.  I believe it has to be repackage for that version.

**Comment by matthewlswanson** [comment]
I figured, just thought I would check for fun! Let me know if you want me to do any testing in the future.  Got maybe 80% of the packages installed.

**Comment by augustf** [comment]
@matthewlswanson You could do something evil, like unpack and modify the deb package in place:

```
dpkg-deb -R original.deb tmp
# edit DEBIAN/CONTROL
dpkg-deb -b tmp fixed.deb
```
