### ISSUE TITLE
Valid RSS feed throws error

### ISSUE THREAD

**Issue by ddbruce** [concerto/concerto#1386]
When I submitted [RPI's alert RSS feed](http://alert.rpi.edu/data/alert/alerts.xml) to my emergency alerts feed, I got the following errors:

`Unable to preview. Permission denied @ unlink_internal - /usr/share/concerto/tmp/cache/224/771/http%3A%2F%2Falert.rpi.edu%2Fdata%2Falert%2Falerts.xml`

and, upon submission:

![image](https://cloud.githubusercontent.com/assets/5694673/23372086/35c233a2-fce8-11e6-9941-d125a4baab2d.png)

Afaik, the above link _is_ a valid RSS feed, and it _has_ worked properly in the past.

**Comment by mfrederickson** [comment]
fyi, here is the current content of that link... (for help in debugging the problem)
```

<?xml version="1.0"?><rss version="2.0" xml:base="http://alert.rpi.edu"  xmlns:dc="http://purl.org/dc/elements/1.1/">
<channel>
<title>RPIalert - alert</title>
<link>http://alert.rpi.edu</link>
<description></description>
<language>en</language>


</channel></rss>
```

**Comment by mfrederickson** [comment]
@ddbruce everything I've seen relating to that error indicates a permissions issue on the file system.  I am able to preview and submit that empty feed just fine.  I would recommend that you check the file permissions on the file or it's directory against what user the web server is running as and make any changes as necessary.

I'd even try a `RAILS_ENV=production bundle exec rake tmp:clear` in the /usr/share/concerto directory (probably as root) and then go back into concerto and try to add that content again.

**Comment by ddbruce** [comment]
@mfrederickson Everything is set to www-data:www-data, and I assume that's correct. None of the files I noticed have execute privileges, but I don't think that's an issue because nothing is executable.

I tried running your suggested command and got no change.

**Comment by augustf** [comment]
You'll want to make sure the tmp directory in the concerto directory (usually /usr/share/concerto/tmp or /var/www/concerto/tmp) exists and is fully writable. That's definitely a filesystem permissions issue. You can always try chmod -R 777 on the directory to open everything up and narrow it down from there.

**Comment by ddbruce** [comment]
@augustf That did fix it. I noticed there was one folder within that was root:root with weird permissions. Now it's all good. Thanks!
