### ISSUE TITLE
frontend using stale cache

### ISSUE THREAD

**Issue by mfrederickson** [concerto/concerto#1393]
We should make sure that when content changes, that the frontend uses it instead of the older cached copy.  Perhaps make sure the etag is set for the index and show actions in the frontend/contents_controller?

See the issue details from the forum https://groups.google.com/forum/#!topic/concerto-digital-signage/t2nMPOpk8Qs

**Comment by mfrederickson** [comment]
The etag for the contents.json is including the hash of the ids of the content, so when content is added or removed it will invalidate the cache-- but not when the contents of the content is changed (which kind of supports the argument that content once submitted should not be changed).

There does not appear to be any etag for the content itself, so I'm going to use a hash of the content contents for that which should cause changed content to appear sooner than later.

**Comment by GreenItSolutions** [comment]
In a same manner, we had a similar bug with Google Spreadsheets modified by multiple users in less than a minute and displayed on concerto frontend.
As a workaround, we made some PHP Code to download on Concerto Server the HTML archive of the Google Spreadsheet and point Concerto Frontend to this internal webpage.
We have no knowledge on coding with ruby, but if you want, i can give your our code to create a similar plugin in Concerto.
Our code is a PHP form to enter Google SpreadSheet URL, download and unzip the html version, extract sheet names, select the sheet to display, and select the refresh time to re download the html version of the google spreadsheet. After that, the user can copy/paste to concerto new content the internal url of this html page with an javascript code to redownload at each refresh timer.
Hope this can be a new concerto plugin.
