### ISSUE TITLE
Add Content Screen, Allowed Content Types and Feeds - Clear Workflow needed.

### ISSUE THREAD

**Issue by taras-yorku** [concerto/concerto#1401]
Adding Content is very confusing. Add button opens a new Content Form with Allowed Content Types are listed at the top. There is no way to tell which other types are allowed or on which feed. 

Per Feed Content Type restriction makes sense, but the whole process of adding content needs to be more clear. For example, Clicking on Browse should show feeds, then clicking on feed should display feed details, along with list of allowed content types and disabled content types, then add content button should utilized. 

Alternatively, Add Content Should allow all content types and then limit the Submit to feed functionality based on the selected content type and allowed content types in the feed. 

I think we should decide on one or the other or both (with both option incorporating the alternative option mentioned above)

The main reason for this is after installing concerto I spent two days trying to figure out why iFrame content type wasn't showing up. Only after looking through source code did I realize that there is an allowed_type restriction. And the only way to know what it is, is to click Browse -> Feed in question -> Edit Feed. 

And when you have to feeds, that restriction is applied in a mysterious way.

**Comment by echathaz** [comment]
When you create a new feed it lists the options for allowed content type.
When you go to add content from the main page, all content types are
allowed the only restriction is when you go to add the new content to a
feed, the feeds that do not allow that content type are not shown. I'm not
certain where the confusion is at.

**Comment by tdak** [comment]
If you only have one feed, and disable some content type, it will not be visible in the add content form. I.e if you disallow iframe, it will not show up in the add content screen. 

Also, when viewing a feed, there is no way to tell what is allowed unless you click on edit feed. 

Incidentally, is there a way to re-order content in the feed?

**Comment by tdak** [comment]
To Illustrate my point. Brand new installation:

There is one feed
![screen shot 2017-03-09 at 3 42 36 pm](https://cloud.githubusercontent.com/assets/366597/23769936/132cb5c0-04df-11e7-91e3-98e54ac2805c.png)

Detail view of feed has no indication what type of content is allowed

![screen shot 2017-03-09 at 3 42 29 pm](https://cloud.githubusercontent.com/assets/366597/23769934/1327d2e4-04df-11e7-9410-abd4c64d706b.png)

Adding content, there is no option for iFrame or Calendar
![screen shot 2017-03-09 at 3 42 22 pm](https://cloud.githubusercontent.com/assets/366597/23769937/132c9734-04df-11e7-80b8-2b11b4a4425f.png)

Even though the plugins are enabled. 

![screen shot 2017-03-09 at 3 42 05 pm](https://cloud.githubusercontent.com/assets/366597/23769935/1328258c-04df-11e7-9e3f-ff222f3dbe66.png)

So it's a bit confusing. The whole process of adding content, submitting it to feeds and assigning feeds to screens needs a bit more refinement.
