### ISSUE TITLE
Added a plugin - Concerto Content Scheduling and it killed concerto

### ISSUE THREAD

**Issue by tdak** [concerto/concerto#1402]
Added a Concerto Plugin through the interface, it was in the list of concerto plugins. Now can't get to any page without the error page popping up.

**Comment by mfrederickson** [comment]
@tdak that's not much to go on.  Do you have an log entries or screenshots?

**Comment by tdak** [comment]
![screen shot 2017-03-09 at 3 39 54 pm](https://cloud.githubusercontent.com/assets/366597/23769830/ade7874e-04de-11e7-860f-5c260b378208.png)

Added that plugin and after that I was receiving error message no matter which page I tried.

**Comment by mfrederickson** [comment]
Can you show me the contents of your /usr/share/concerto/logs/production.log?

**Comment by tdak** [comment]
Don't have it anymore, it was a vagrant install so I blew it away and re-installed it. I will try it again tomorrow, see if I get the same error

**Comment by tdak** [comment]
This happens when Frequency is set. But I was getting standard 500 rails error message before. 

![screen shot 2017-03-09 at 3 58 22 pm](https://cloud.githubusercontent.com/assets/366597/23770491/45970662-04e1-11e7-9d02-b56fd92899ae.png)

**Comment by mfrederickson** [comment]
Is this concerto 2.3.4 on debian jessie ?

**Comment by tdak** [comment]
Latest concerto on Ubuntu 16.4 LTS

**Comment by mfrederickson** [comment]
@tdak I just tried it from a fresh clone of the repo, (so development environment) and it worked fine.  I do not know how to do a vagrant install with apt-get, can you walk me through that so I check it out?  Thanks.

**Comment by mfrederickson** [comment]
@tdak I was able to `vagrant up bento/ubuntu-16.04` and install concerto-full and then I added a piece of content.  Then I added the concerto content scheduling plugin, manually precompiled the assets, and changed the owner, and restarted apache (see below). I was able to add scheduled content just fine.

```
vagrant ssh
sudo bash
cd /usr/share/concerto
RAILS_ENV=production bundle exec rake assets:precompile
chown -R www-data:www-data *
service apache2 restart
exit
exit
```

**Comment by tdak** [comment]
@mfrederickson I followed the install from wiki page 

1) curl get.concerto-signage.org/add_repo.sh | sh
2) sudo apt-get install concerto-full

But I don't think the install matters.  In any case. I was trying to repeat the steps and everything seems to work fine now. Maybe there was a bug and it got fixed. If I come across it again, I'll do more screenshots and dig through the log better.
