### ISSUE TITLE
Show on Screen range too limited for some content

### ISSUE THREAD

**Issue by techitch-IT** [concerto/concerto#1408]
The 12s max duration for static content types is excessively short.  Text or other detail-rich content often demands more than 12s of duration for an effective sign in applications I'm working with.  The slider is a great, easy way for quick content entry, but an accompanying/alternative text box could allow for acceptable ease of use while allowing longer times to be entered.  In any case, allowing durations up to 60s (or even longer?) is wanted for some static content/use cases.

**Comment by mfrederickson** [comment]
@turnpointg check the content settings-- you can change this

**Comment by turnpointg** [comment]
Boy do I feel silly.  Thanks @mfrederickson!  That took care of it for me.
