### ISSUE TITLE
Create new Templates

### ISSUE THREAD

**Issue by maikwoehl** [concerto/concerto#1442]
I want to create a new template, but don't know how and where the current template is located. Is there an example template to start with?

Are there any resources of this kind?

Thank you

Best regards

Maik

**Comment by mfrederickson** [comment]
They are stored in the database.  Check these resources:

https://youtu.be/5IAnS-ib9R8
https://github.com/concerto/concerto/wiki/Templates
https://groups.google.com/forum/#!searchin/concerto-digital-signage/template%7Csort:relevance
