### ISSUE TITLE
Sharepoint RSS Feed not Accepted

### ISSUE THREAD

**Issue by newsupast** [concerto/concerto#1452]
Hello there, 

it seems like the conerto server cannot handle the Microsoft Sharepoint generated RSS feeds.

When trying to add the RSS Feed of the Sharepoint as "Content" i get the following error:

![firefox_2017-07-13_11-01-10](https://user-images.githubusercontent.com/12899154/28158656-b98d42fc-67ba-11e7-9471-9c8f30893aaa.png)

The URL (censored a bit for privacy)

http://xxx/websites/xxx/_layouts/listfeed.aspx?List=%7B4816CEB1%2D50B0%2D4306%2D85CB%2DB2D63159844E%7D

**Comment by mfrederickson** [comment]
What version of sharepoint?

**Comment by mfrederickson** [comment]
@newsupast I wonder if it is not authenticating (but also not clearly telling you that)...?

**Comment by mfrederickson** [comment]
@newsupast I was able to get a sharepoint RSS feed to work-- but I had to use the latest concerto-simple-rss (master branch).  I had to specify authentication credentials in the fields when setting up the content.

**Comment by newsupast** [comment]
@mfrederickson Thank you for your Quick replies, i have been away for the last 2 weeks, sorry for not getting back to you.

The Sharepoint Version we are using is "12.0.0.6545".

It requires Authentication, however have tried setting up a mirror version with authentication disabled, and we are encountering the same problem there.

If we try to add the RSS Feed that needs authentication with our "concerto user", we are getting the following error message:

![chrome_2017-07-24_12-52-25](https://user-images.githubusercontent.com/12899154/28520362-7b88da26-706f-11e7-80a2-82ace6cb83a6.png)

If we try to add the content without providing authentication, we get the error message of my first post.

We are unfamiliar with the magic that is linux, and have ran into a few unresolvable errors while trying to use the "apt-get install concerto-full" method, specifically some dependencies like ruby-mysql not being found, so we have opted to use the workin VM image instead. 

Could you give us a brief explanation of how we would go about if we wanted to use the latest concerto-simple-rss ?

Thanks in advance,
newsupast

**Comment by mfrederickson** [comment]
Well, probably the easiest way is to go to Plugins and change the
concerto-simple-rss to point to the git repo to get the latest (master
branch), as shown below.  And then restart the apache webserver or reboot
the machine.

https://github.com/concerto/concerto-simple-rss.git

[image: Inline image 1]

The only drawback is that you are using the master branch which is a
"development" branch.  Once the gem is rebuilt and released then you could
just use that-- but I'm not sure when that will be.  You can switch over to
it when it comes out, just remember to do so.

PLEASE NOTE THAT THIS VERSION IS NOT BACKWARDS COMPATIBLE WITH THE
ENCRYPTION USED FOR THE USER/PASSWORD IN SECURED RSS FEED CONTENT.  WHAT
THIS MEANS IS THAT IF YOU HAVE ANY RSS FEED CONTENT THAT YOU HAD TO SUPPLY
A USER AND PASSWORD FOR THEN YOU WILL NEED TO EXPIRE OR DELETE THAT CONTENT
AND RE-ADD IT.  [newsupast this should not apply to you.]

**Comment by newsupast** [comment]
We have updated the Plugin to pull directly from the Git, however the problem still persists, as we are still getting the encryption error i linked in the second post. What exactly does this error message mean ? That the credentials provided are wrong ?

**Comment by mfrederickson** [comment]
Did you reboot the concerto server after you updated the plugin?

The "encrypt" error means that the gem (code module) behind the scenes was updated and that method was made obsolete.  The new version fixes that problem.

**Comment by newsupast** [comment]
Yes we did, is there a way to check the current version that it is using ? It says that its pulling from the Git, but is there any way to check ? I could imagine it defaulting back to the original ruby gem after failing to get the latest version from Git

**Comment by mfrederickson** [comment]
Can you show me the contents of the /usr/share/concerto/Gemfile-plugins
file?

**Comment by newsupast** [comment]
This is the "more" of the file

![virtualbox_2017-07-27_08-46-57](https://user-images.githubusercontent.com/12899154/28657641-5a37383c-72a8-11e7-92dd-71916108bc91.png)

**Comment by mfrederickson** [comment]
@newsupast  I apologize for such a late response.  We use AD here also.  I'm using version 2.3.6 and here are the screenshots. The short domain in the login used, is KPB.

You can see that the preview worked here.  Do you get this far?
![selection_342](https://user-images.githubusercontent.com/473165/37434411-558e303c-2794-11e8-8206-87a1f948c2e2.png)

This is from sharepoint, directly.
![selection_343](https://user-images.githubusercontent.com/473165/37434527-b56b35fe-2794-11e8-8431-6d580e9b92f4.png)

And here it is, on the screen:
![selection_344](https://user-images.githubusercontent.com/473165/37434457-7d6425a8-2794-11e8-9e00-b6331db9dec6.png)
