### ISSUE TITLE
Time clock affecting RSS feeds

### ISSUE THREAD

**Issue by dtroth** [concerto/concerto#1453]
Whether on Ubuntu server, or VirtualBox setup, RSS feeds don't display if the time zone is set in a specific time. I am in Central Time (GMT -6) and it will not populate a field pulling from an RSS feed. If set to Eastern Time or UTC, it works.
I am running Concerto 2.3.4, all plugins up to date. Ubuntu server 16.04, but also ran on Virtual Box and did apt-get upgrade.

**Comment by mfrederickson** [comment]
Timezone on the OS, the System Settings (in concerto), or the screen (in concerto).  What is the timezone on the screen device?  Does it match the timezone on the screen setup?

**Comment by dtroth** [comment]
When I set up a screen (computer, pi, player), it asks for the timezone of the screen. It's that time setting that's affecting the RSS.

**Comment by mfrederickson** [comment]
@dtroth I am unable to reproduce this problem.  I've tried with my timezone (Alaska) and yours.  I am running version 2.3.6.  My OS timezone is set to AKDT, but my Concerto settings timezone was changed as was the screen timezone to CST and the RSS feed displayed fine.

Can you tell me if 1) it still happens on version 2.3.6 for you, and 2) if you have the Concerto Settings timezone set to the same (CST) and your screens?  Thanks.
