### ISSUE TITLE
Screen does not cycle content on Chrome displays.

### ISSUE THREAD

**Issue by rdohms** [concerto/concerto#1454]
I saw a few mentions of this but they all went a separate way and none seem to have addressed the chrome issue.

Currently with version 2.3.3 on a Chrome display the screen does not cycle the content. It works just fine on safari, but we run chromium on our displays.

i see this in console:
```
Uncaught TypeError: Failed to execute 'animate' on 'Element': 'function (a){return a}' is not a valid value for easing
```

Any idea on what the issue is?

**Comment by mfrederickson** [comment]
That's been fixed a while ago-- you'll need to upgrade the frontend plugin.  Read the postings here https://groups.google.com/forum/#!searchin/concerto-digital-signage/animate%7Csort:relevance/concerto-digital-signage/7DR-6psl3BU/xxACYOp2AgAJ

**Comment by rdohms** [comment]
Indeed updating the frontend gem did solve it, thanks!
