### ISSUE TITLE
No package for Debian Stretch

### ISSUE THREAD

**Issue by ghost** [concerto/concerto#1458]
Hi Team,

the Debian Package is for Debian Jessie which is the oldstable. The packege cannot be installed on Debian Stretch because of missing packeges (probably due to renamed packeges)

"The following packages have unmet dependencies: 
 concerto-full : Depends:  ruby-mysql but it is not installable
                        Depends: libmysqlclient-dev  but it is not installable
E: Unable to correct problems,you have held broken packages."

**Comment by tlehtil** [comment]
The new names in Stretch are:
_ruby-mysql_ is named _ruby-mysql2_  https://packages.debian.org/stable/ruby-mysql2 and the _libmysqlclient-dev_ is named _default-libmysqlclient-dev_  https://packages.debian.org/stable/default-libmysqlclient-dev

**Comment by mfrederickson** [comment]
See https://github.com/concerto/concerto-debian/issues/69.  The latest version is available for Debian Stretch.
