### ISSUE TITLE
dl.concerto-signage.org cert expired

### ISSUE THREAD

**Issue by mfrederickson** [concerto/concerto#1464]
This server could not prove that it is dl.concerto-signage.org; its security certificate expired 295 days ago. 

We should set up a self-renewing free SSL cert from letsencrypt.org.

**Comment by hrak** [comment]
The same goes for https://get.concerto.org which is mentioned in the documentation/README.

**Comment by mfrederickson** [comment]
@augustf can I get login rights to these servers so I can set up free, auto-renewing SSL (using letsencrypt.org)?

**Comment by bamnet** [comment]
dl.concerto-signage.org is relatively happy now.  I run it on a server that hosts a few other production sites, so I'm likely to notice when it's down.
