### ISSUE TITLE
Permissions problem

### ISSUE THREAD

**Issue by robp2175** [concerto/concerto#1465]
Users cannot edit their own submissions.

For some reason users are not able to edit their own submissions. 

They were able to do this before, but all of a sudden inexplicably this seems to have stopped.

Any assistance to figure out what is going on would be appreciated.

**Comment by mfrederickson** [comment]
@robp2175  That is correct.  Normal users can edit their content until it is approved.  Approved content cannot be edited by a normal user as that would defeat the purpose of the approval process.  If the user has the ability to moderate (approve) all of the feeds to which the content was submitted, then it can be edited by them.  It was addressed in this issue back in March 2017.  

https://github.com/concerto/concerto/issues/1392

Hope this helps.  Please close if so.

**Comment by robp2175** [comment]
Thank you for the explanation, I appreciate it.
