### ISSUE TITLE
Upgrade from 2.3.3 to 2.3.5 ruined RSS Feed Content (XML, XSLT)

### ISSUE THREAD

**Issue by robp2175** [concerto/concerto#1466]
Because I wanted a very customized weather feed, I created my own rss, xslt and used the RSS content type.

I decided to finally upgrade to 2.3.5 which seemed to go fine, except now my weather feeds look like garbage. The before and and after and be viewed in these links

As you can see the formatting is a mess and images no longer show up. Has anyone else had this issue.
As always, thank you for any assistance. 

You will need to copy paste this link.
[https://imgur.com/a/IHTU4](url)

My RSS code
```
<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
    <rss version="2.0" xmlns:yweather="http://xml.weather.yahoo.com/ns/rss/1.0" xmlns:geo="http://www.w3.org/2003/01/geo/wgs84_pos#">
						
	<channel>

		<title>Conditions for Bangor, ME, US at 08:00 AM EST</title>
			<description>Weather for Conditions for Bangor, ME, US at 08:00 AM EST</description>
				<language>en-us</language>

			
	<yweather:location city="Bangor" region=" ME"   country="United States"/>
	<yweather:units temperature="F" distance="mi" pressure="in" speed="mph"/>
	<yweather:wind chill="23"   direction="270"   speed="4" />
	<yweather:atmosphere humidity="82"  pressure="1021.0"  rising="0" />
	<yweather:astronomy sunrise="6:51 am"   sunset="3:56 pm"/>

		<item>
			<title>Conditions for Bangor, ME, US at 08:00 AM EST</title>
			<geo:lat>44.801708</geo:lat>
			<geo:long>-68.770767</geo:long>
			<pubDate>2017-11-30 9:45 am EST</pubDate>
			<yweather:condition  text="Partly Cloudy"  code="30d"  temp="23"  date="Thu, 30 Nov 2017 08:00 AM EST" high="40" low ="19" />

			<description><![CDATA[
			<img src="http://concerto.domain.edu:81/weather/icons-owm/30d.png"/><br />
			<b>Current Conditions:</b><br />
			Partly Cloudy, 23 F<BR />
			<BR /><b>Forecast:</b><BR />
			Today - Partly Cloudy. High: 40 Low: 19<br />
			Tomorrow - Scattered Showers. High: 45 Low: 33<br />
			Sat - Partly Cloudy. High: 38 Low: 27<br />
			Sun - Mostly Cloudy. High: 38 Low: 25<br />
			Mon - Partly Cloudy. High: 39 Low: 26<br /><br />
			]]></description>

			<yweather:forecast day="Fri" date="01 Dec 2017" low="33" high="45" text="Scattered Showers" code="39d" />
			<yweather:forecast day="Sat" date="02 Dec 2017" low="27" high="38" text="Partly Cloudy" code="30d" />
			<yweather:forecast day="Sun" date="03 Dec 2017" low="25" high="38" text="Mostly Cloudy" code="28d" />
			<yweather:forecast day="Mon" date="04 Dec 2017" low="26" high="39" text="Partly Cloudy" code="30d" />
			<yweather:forecast day="Tue" date="05 Dec 2017" low="29" high="45" text="Scattered Showers" code="39d" />
			<guid isPermaLink="false"></guid>
		</item>
	</channel>
</rss>
```

XSLT:
```
<?xml version="1.0" encoding="ISO-8859-1"?>

<xsl:stylesheet version="1.0"
		xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:yweather="http://xml.weather.yahoo.com/ns/rss/1.0" xmlns:geo="http://www.w3.org/2003/01/geo/wgs84_pos#">
<xsl:output method="html" indent="yes"/>

<xsl:template match="/">

<xsl:variable name="scale">
    <xsl:value-of select="rss/channel/yweather:units/@temperature"/>
</xsl:variable>

<table width="100%" border="0" class="Normal">
  <tr>
    <td colspan="2" align="center" style="white-space:nowrap; font-size: 2.0vw;"><strong>Bangor Weather Report</strong></td>
  </tr>
  
  <tr>
    <td><div style="margin: 10px 0 0 0;height: 150px;">
      <xsl:text disable-output-escaping="yes">&lt;img src="http://concerto.domain.edu:81/weather/icons/</xsl:text>
      <xsl:value-of select="rss/channel/item/yweather:condition/@code"/>
      <xsl:text disable-output-escaping="yes">-lg.png"/&gt;</xsl:text> </div>
     </td>
	 <td style="vertical-align: top;"><div style="margin: 40px 0 0 0; line-height: 1.2vw; font-size: 2.6vw;"><strong>
	 <xsl:value-of select="rss/channel/item/yweather:condition/@temp"/><div style="margin: 0 5px 0 2px; display:inline;  position: relative; top: -2vh; font-size: 1vw"><sup><xsl:text>o</xsl:text></sup></div><xsl:copy-of select="$scale" />
	 </strong><br /></div>
      <div style="line-height: 1.6vw;font-size: 1.4vw"><xsl:value-of select="rss/channel/item/yweather:condition/@text"/><br />
	  High: <xsl:value-of select="rss/channel/item/yweather:condition/@high"/><xsl:text></xsl:text><xsl:copy-of select="$scale" /><br />
      Low: <xsl:value-of select="rss/channel/item/yweather:condition/@low"/><xsl:text></xsl:text><xsl:copy-of select="$scale" />
	   </div>
	   </td>  
  </tr>
  <tr>
    <td colspan="2">
		<table align="center" width="100%" border="0" class="Normal">
			<xsl:for-each select="(rss/channel/item/yweather:forecast)[position() &lt; 4]">
				<tr>
					<td> <div style="margin: 0px 0 5px 0px; font-size: 1.8vw;font-weight: bold; transform : scale(1,1.5);-webkit-transform:scale(1,1.5);-moz-transform:scale(1,1.5);-ms-transform:scale(1,1.5);-o-transform:scale(1,1.5); ">
					<xsl:value-of select="@day"/>	
					</div></td>

					<td style="width: 125px;">
					<div style="margin: 25px 0 0 30px;"><xsl:text disable-output-escaping="yes">&lt;img src="http://concerto.domain.edu:81/weather/icons/</xsl:text>
						<xsl:value-of select="@code"/>
						<xsl:text disable-output-escaping="yes">.png"/&gt;</xsl:text></div>
					</td>
					<td style="text-align: left;" >
						<!--<div style="font-size: 1.8vw;font-weight: bold;"><xsl:value-of select="@day"/><br /></div>-->
						<div style="line-height: 1.6vw;font-size: 1.4vw;"><xsl:value-of select="@text"/><br/>
						High: <xsl:value-of select="@high"/><xsl:text>&#176; </xsl:text><xsl:copy-of select="$scale" /><br />
						Low: <xsl:value-of select="@low"/><xsl:text>&#176; </xsl:text><xsl:copy-of select="$scale" /></div>
					</td>
				</tr>
			</xsl:for-each>
      </table>
	</td>
  </tr> 
</table>

</xsl:template>

</xsl:stylesheet>
```

**Comment by salfter** [comment]
I was looking into upgrading from 2.3.3 to 2.3.5 as it seems that the latest versions of Chromium and Firefox no longer with with 2.3.3 (the screen never updates).  I upgraded to 2.3.5, and while the screen updates again, none of our news feeds (supplied by RSS) are showing up.  They're still getting updated, but they never show up on a screen.

**Comment by mfrederickson** [comment]
@salfter do they show up when you preview the screen while logged into concerto web?

**Comment by mfrederickson** [comment]
@robp2175 I think you need the concerto-weather update, and then recreate your weather feed.  Let me find the link...

**Comment by mfrederickson** [comment]
See https://github.com/concerto/concerto-weather/issues/42

**Comment by robp2175** [comment]
Thank you for getting back to me Marvin, and apologies for the amount of time it took. I ended up reverting back to 2.3.3 because I didnt have time to wokr through the issue, but Concerto is no longer updating on more modern browsers on 2.3.3 so I have upgraded to 2.3.6. This issue is now an absolute priority for me because I had to disable all of my RSS Feeds until this is resolved. 

I went ahead and updated the Weather plugin. However, I do not use the weather plugin. I actually use a custom RSS Feed. Therefore, I also update the concerto-simple-rss plugin in the same manner. Unfortunately, there is no change, all of my RSS Feeds have stopped looking proper. None of them will display any of the images, and they all look terrible. I am using th exact same code you see above. 

As always Marvin, I really appreciate your time and effort, you have always been a huge help to me.

**Comment by robp2175** [comment]
Marvin, you should also be aware that no RSS Feed I have tied will show images since the upgrade. The pictures show up and everything looks good in the preview pane, but on the screen there are no pictures.

For example, this is one we use
 http://www.librarything.com/rss/recent/EMCCLibrary


I found this one for another example, 
http://rssfeeds.usatoday.com/usatoday-newstopstories&x=1

**Comment by robp2175** [comment]
Marvin, I think I just figured out what is happening (sort of). The RSS Feed is displayed in text Field. It appears as though Text fields will no longer allow pictures at all for some reason. Something in the code changed to prevent this. I tried to change the field type to dynamic, but then nothing showed up.

**Comment by mfrederickson** [comment]
Confirmed.  Looks like it might have been sanitized/filtered out.  I will look at the diff between releases...

**Comment by robp2175** [comment]
FYI/Reminder, I went from 2.3.3 directly to 2.3.6.

**Comment by salfter** [comment]
Took another whack at 2.3.5 a while ago...this time, I did a clean install in a new VM and moved our data from the old 2.3.3 install to the new 2.3.5 install.  Weather and news feeds are working the same as they did, so maybe there's an issue with upgrading vs. clean install.

(IIRC, I'm using the provided VM image...took a bit of persuasion to get VMware to take it, but it's working.)

**Comment by mfrederickson** [comment]
@robp2175 would you be willing to go into /usr/share/concerto/app/models and apply the two changes to in the pull request mentioned above (remove one line from text_content.rb and change one line in ticker.rb), and restart your server and force update the children and let me know how it goes.  Maybe check out/test your other text/ticker content and see if there are any adverse impacts to this change.  I've already tested it myself manually and via the test cases, and it looks good to me, but extra testing wouldn't hurt.  If you need help implementing this, please let me know.  Thanks.

**Comment by mfrederickson** [comment]
@salfter I wonder if the rss feed had a chance to update (using the newer 2.3.5 code, which happens to strip out a bunch of html tags and attributes).  In your installation, would you mind adding the EMCC RSS feed from Rob's comment above (since it includes images and has been shown to expose the problem) as a 'detail' display type and submit it to a test feed/screen and then preview the screen and see if you see any images? I think each article has an image of a book.  I believe this has been broken for quite a while but is only exposed under certain conditions.  I'd appreciate hearing how it goes.  Thanks.

**Comment by robp2175** [comment]
Marvin, you are a magician! Works perfectly. Thank you so much. I am actually really surprised noone else ran into this issue. Thanks again sir.
