### ISSUE TITLE
configuration instructions for system use

### ISSUE THREAD

**Issue by mirandadelima** [concerto/concerto#1467]
Good afternoon sir mfrederickson

First congratulations for the development of digital signage CONCERTO.

We have just installed a server with the service, so we would like to have access to information / forum configuration instructions for system use.

In case of translating into Portuguese-BR you can count on us, just send the file that I do without any problem.

Sincerely

**Comment by mfrederickson** [comment]
Someone on the forum may have a guide or be able to answer your questions.  
https://groups.google.com/forum/#!forum/concerto-digital-signage
