### ISSUE TITLE
No mail for moderation request

### ISSUE THREAD

**Issue by rtorrente** [concerto/concerto#1468]
When content is submitted requiring moderation, I'm not receiving any of the notifications. Sendmail is working correctly and I receive the test email when i run the "Check Configuration".
Receive email moderation is enabled in my moderator profile..
There is nothing on the production.log talking about email ..

**Comment by mfrederickson** [comment]
@rom do you have it checked for both the user's group membership and the user itself?
![image](https://user-images.githubusercontent.com/473165/33970446-9c68c9e8-e01f-11e7-8b51-61fe350ed1f5.png)
![image](https://user-images.githubusercontent.com/473165/33970561-30a0f81a-e020-11e7-9265-1370db6bab77.png)

**Comment by rom650** [comment]
Hello @mfrederickson yes it's checked like you on the both page (user and group) :/

**Comment by mfrederickson** [comment]
@rom650 silly question, but want to confirm that you are adding a piece of content and submitting it to a feed as a user that does not have admin or moderation rights.
