### ISSUE TITLE
Clock blinking in and out

### ISSUE THREAD

**Issue by whippc** [concerto/concerto#1470]
It seems the clock field wants to blink in and out like its refreshing every 5 seconds. I have tried setting the transition but it doesnt help.

**Comment by timparenti** [comment]
This sounds as though it may be a duplicate of #1451.

**Comment by mfrederickson** [comment]
Thanks @timparenti.  This is a duplicate. Closing.  @whippc I'd recommend using Chrome if you can-- doesn't appear to happen with it.
