### ISSUE TITLE
Screen Online/Offline problem

### ISSUE THREAD

**Issue by rtorrente** [concerto/concerto#1472]
Everything is working fine and all screen are ON et contents updated in real time but the Screen page not show screen as online. 
The amount of screens online and offline are changing drastically every few minutes and are switching between black and blue whilst refreshing the screens page. It is showing many of the screens that are online and working as offline.

**Comment by mfrederickson** [comment]
Can you also tell me if the screens are set up as "publicly viewable" or not, and what authentication you have specified for the screens?  What timezone do you have set up on your server OS, the concerto settings, and the screens in question?

The code that determines if a screen is online is in app/models/screen.rb
```
  def is_online?
    !frontend_updated_at.nil? && frontend_updated_at >= (Clock.time - Screen::ONLINE_THRESHOLD)
  end
```
And the `ONLINE_THRESHOLD` is set for 5 minutes, and `Clock.time` simply calls `Time.now`.  The `frontend_updated_at` is updated to `Clock.time` initially when the screen is first displayed (in app/controllers/screens_controller.rb) and then occasionally when a list of content is requested for a field (in app/controllers/frontend/contents_controller.rb).
