### ISSUE TITLE
Seperate feeds for each different field with same type as another field

### ISSUE THREAD

**Issue by Luneya** [concerto/concerto#1473]
I am trying to make a digital signage system in our office to display some internal stats, the weather and news headlines.

Our national 'shower radar' has a nice HTML5 widget displaying oncoming spells of rain. I wanted to display that in a Graphic field on the left. I also want to display the internal stats via webpages I make outside of concerto and display those on other parts of the screen.

I made two seperate feeds: One with the stats pages as iframes and one with the weather widget as iframe.

I expected to be able to set one feed to one specific Graphic field, and the other feed to the other field with the same type. This is where I am getting confused - because that does NOT seem to be the case.

![knipsel](https://user-images.githubusercontent.com/25928554/35389541-5f452c20-01d8-11e8-89a3-224962c10365.JPG)

Fields with identical types can not be filled seperately.. Is this meant to be the case, or a bug? Either way, this software is not usable in my case like this. I need to be able to display different feeds of content on different places without the content showing up in all fields with the same type.

How do I proceed to make this work?

**Comment by mfrederickson** [comment]
@Luneya are you running version 2.3.6?

I was able to create another field called Graphics2
![image](https://user-images.githubusercontent.com/473165/37371622-d6a53100-26c4-11e8-8850-c692a99df70f.png)

and add a position to the template for that field
![image](https://user-images.githubusercontent.com/473165/37371642-e7cccec0-26c4-11e8-84f7-65396ee1f1d0.png)

and then subscribe different feeds to each graphics field
![image](https://user-images.githubusercontent.com/473165/37371715-26d616da-26c5-11e8-83ee-cd2d827895cd.png)

![image](https://user-images.githubusercontent.com/473165/37371740-43456f82-26c5-11e8-8dfa-32cc57915f6d.png)

**Comment by matthewlswanson** [comment]
I can confirm this works as I use this same process for some of my screens.

**Comment by mfrederickson** [comment]
Thanks @matthewlswanson .
