### ISSUE TITLE
Issue with rake db:migrate

### ISSUE THREAD

**Issue by OuBi3n** [concerto/concerto#1474]
Hi all,

On a fresh install of concerto (package method) on debian 9, i've got some troubles with rake db:migrate.
`# rake db:migrate
rake aborted!
Mysql2::Error: Access denied for user 'my_username'@'local'host'`
Thanks a lot for the help.

**Comment by OuBi3n** [comment]
i've resolve my problem, then a new issue is coming when i run rake db;migrate :
`Mysql2::Error:` Specified key was too long; max key length is 767 bytes : CREATE UNIQUE INDEX ìndex_users_on_email` ON `users` (`email`) /usr/share/concerto/vendor/bundle/ruby/2.3.0/gems/mysql2-0.4.9/lib/mysql2/client.rb:120:in `query'`

**Comment by garlicPasta** [comment]
Same problem here. I switched to sqlite to bypass the problem.

**Comment by OuBi3n** [comment]
resolved ! -> new installation !
