### ISSUE TITLE
Run program produces 404 error

### ISSUE THREAD

**Issue by liezelkorf** [concerto/concerto#1475]
Hi
I installed the Concerto platform for computer adaptive testing. Everything seems to have worked fine. (All green ticks). However, when I try to run it, it gives a 404 error message.
Not Found
The requested URL /concerto-platform/admin was not found on this server.
Apache/2.4.17 (Win64) PHP/5.6.16 Server at localhost Port 80
Can someone please assist?

**Comment by mfrederickson** [comment]
@liezelkorf this repo is for concerto digital signage.  This is not related to http://concertoplatform.com/
