### ISSUE TITLE
Dashboard 500 Error:  Unable to determine latest available version.

### ISSUE THREAD

**Issue by chamblissb** [concerto/concerto#1479]
Getting a 500 error on the dashboard. After a few tries, the dashboard comes up, but I get this error.

![concerto](https://user-images.githubusercontent.com/37554424/37618920-a5f1acba-2baf-11e8-980e-389f504d6d93.PNG)

Production.log file:

I, [2018-03-19T12:58:11.361171 #1307] INFO -- : Started GET "/dashboard" for 192.168.95.73 at 2018-03-19 12:58:11 -0500
 I, [2018-03-19T12:58:11.361840 #1307] INFO -- : Processing by DashboardController#show as HTML
 I, [2018-03-19T12:58:11.388989 #1307] INFO -- : Downloading latest Concerto version information for the first time.
 I, [2018-03-19T12:58:11.539295 #1307] INFO -- : Completed 500 Internal Server Error in 177ms (ActiveRecord: 1.9ms)
 F, [2018-03-19T12:58:11.544000 #1307] FATAL -- :
 NoMethodError (undefined method tag_name' for #<String:0x0055b97cc4e2b8>): lib/version_check.rb:14:inlatest_version'
 app/controllers/dashboard_controller.rb:43:in show' app/controllers/application_controller.rb:112:inset_time_zone'

**Comment by mfrederickson** [comment]
@chamblissb is this on the vm or did you install concerto another way?

**Comment by chamblissb** [comment]
Installed on Debian Jessie about a year ago.  Upgraded to Debian Stretch.

**Comment by mfrederickson** [comment]
And your server that it is installed on has access to the internet? (It looks up the latest version off of github using Octokit.)

**Comment by chamblissb** [comment]
Tried to get to GitHub using a browser on the server.  Got blocked by our content filter.

That has got to be it.  May also fix some other issues, like the weather not updating.

I'll get it opened up and post the result.

Thanks so much!!

**Comment by chamblissb** [comment]
That was the issue.  
We opened GitHub.com for that server on our content filter and the Dashboard is working now.
