### ISSUE TITLE
some improvement to the install guide

### ISSUE THREAD

**Issue by momolemo** [concerto/concerto#1480]
Hello,
I just try to follow your install guide on the wiki and i have some remarks to improve the doc.

i first try to install on debian 8 and there is a problem with some package that are not availaible at the right version.
maybe In the procedure you can precise that only debian 9 is supported.

for example this package on debian 8 =>
libstdc++6 (>= 5.2) but 4.9.2-10+deb8u1 

Second the script get.concerto-signage.org/add_repo.sh use sudo but on debian it is not available by default so the script crash. Personnaly i edit your script and remove the sudo but maybe an option and a little info on the wiki so the people without sudo who use root directly.

This is not very big problem and it is only to share my experience and i hope help you to improve.

regards

**Comment by mfrederickson** [comment]
The article has been updated.  Thank you.
