### ISSUE TITLE
Reset password feature brings users to a broken page

### ISSUE THREAD

**Issue by matthewlswanson** [concerto/concerto#1483]
When my users use the password reset feature and click the link in their email, it messes up the url and breaks the link. It takes them to https://**myurl**users/password/edit?reset_password_token=********* when it should be taking them to https://**myurl**/users/password/edit?reset_password_token=*********.
Why is the slash before users missing?

**Comment by mfrederickson** [comment]
@matthewlswanson I am unable to duplicate this issue.

**Comment by matthewlswanson** [comment]
![concerto](https://user-images.githubusercontent.com/11579575/40147185-8328ff4e-591d-11e8-8872-f7237203a490.gif)

**Comment by matthewlswanson** [comment]
Video: [https://drive.google.com/file/d/1TlexdyPNcdrvdCXJH_2mayBoXJAvVLmi/view?usp=sharing](url)

**Comment by matthewlswanson** [comment]
Wow I figured it out and it was silly. When we moved the site to https it broke our redirect. Fixed now.
