### ISSUE TITLE
After Manually Inputting Version number in Concerto_weather

### ISSUE THREAD

**Issue by Millator** [concerto/concerto#1484]
In the GUI I inputted .6 as the version number in the concerto_weather plugin, now I am receiving the below screenshot
Any ideas? Really new to rails and gems!
Thanks in advance
 
![concertoerror](https://user-images.githubusercontent.com/17126182/39524826-3e525522-4de8-11e8-90ba-9fa73612a334.png)

**Comment by mfrederickson** [comment]
The production.log file may reveal more information.  It should be under
/usr/share/concerto/logs, if I recall.

**Comment by Millator** [comment]
`I, [2018-04-27T17:04:51.941511 #42452]  INFO -- :   Rendered layouts/_errors.html.erb (0.1ms)
I, [2018-04-27T17:05:08.909616 #42452]  INFO -- : Processing by ErrorsController#render_error as HTML
I, [2018-04-27T17:05:09.786753 #42452]  INFO -- :   Rendered errors/error_generic.html.erb within layouts/no-topmenu (1.3ms)
I, [2018-04-27T17:06:36.184863 #42459]  INFO -- :   Rendered layouts/_errors.html.erb (0.1ms)
I, [2018-04-27T17:06:54.692371 #42459]  INFO -- : Processing by ErrorsController#render_error as HTML
I, [2018-04-27T17:06:55.501832 #42459]  INFO -- :   Rendered errors/error_generic.html.erb within layouts/no-topmenu (1.2ms)
I, [2018-04-27T17:07:14.559427 #42452]  INFO -- :   Rendered layouts/_errors.html.erb (0.1ms)
I, [2018-04-27T17:07:51.621204 #42452]  INFO -- :   Rendered layouts/_errors.html.erb (0.1ms)
I, [2018-04-27T17:08:09.307399 #42452]  INFO -- : Processing by ErrorsController#render_error as HTML
I, [2018-04-27T17:08:10.185895 #42452]  INFO -- :   Rendered errors/error_generic.html.erb within layouts/no-topmenu (0.6ms)
I, [2018-04-27T17:10:49.488094 #42452]  INFO -- :   Rendered layouts/_errors.html.erb (0.1ms)
I, [2018-04-27T17:11:23.767890 #42459]  INFO -- :   Rendered layouts/_errors.html.erb (0.6ms)
I, [2018-04-27T17:13:43.863159 #42452]  INFO -- :   Rendered layouts/_errors.html.erb (2.2ms)
I, [2018-04-27T17:14:03.265321 #42452]  INFO -- :   Rendered layouts/_errors.html.erb (0.1ms)
I, [2018-04-27T17:15:02.036615 #42452]  INFO -- :   Rendered layouts/_errors.html.erb (0.1ms)
I, [2018-04-27T17:15:06.738940 #42452]  INFO -- :   Rendered layouts/_errors.html.erb (0.1ms)
I, [2018-04-27T17:15:10.853732 #42452]  INFO -- :   Rendered layouts/_errors.html.erb (0.1ms)
I, [2018-04-27T17:15:11.005596 #42452]  INFO -- :   Rendered layouts/_errors.html.erb (0.0ms)
I, [2018-04-27T17:15:17.166169 #42452]  INFO -- :   Rendered layouts/_errors.html.erb (0.1ms)
E, [2018-04-27T17:16:56.829278 #42452] ERROR -- : response (http://api.openweathermap.org/data/2.5/forecast/daily?appid=80f850ef8de33cf26142f536e81e481f&cnt=2&lat=36.9623&lon=-120.0595&mode=json&units=imperial) =  {"cod":401, "message": "Invalid API key. Please see http://openweathermap.org/faq#error401 for more info."}
I, [2018-04-27T17:17:40.235074 #42452]  INFO -- :   Rendered layouts/_errors.html.erb (0.0ms)
I, [2018-04-27T17:18:41.670491 #42452]  INFO -- :   Rendered layouts/_errors.html.erb (0.1ms)
I, [2018-04-27T17:18:43.807409 #42452]  INFO -- :   Rendered layouts/_errors.html.erb (0.1ms)
I, [2018-04-30T10:53:48.885429 #43799]  INFO -- : Processing by ErrorsController#render_error as HTML
I, [2018-04-30T10:53:48.894425 #43799]  INFO -- :   Rendered errors/error_404.html.erb within layouts/application (1.1ms)
I, [2018-05-01T10:16:56.035998 #22287]  INFO -- :   Rendered layouts/_errors.html.erb (2.1ms)
I, [2018-05-01T10:17:36.089174 #22287]  INFO -- :   Rendered layouts/_errors.html.erb (0.1ms)
I, [2018-05-01T14:32:30.940950 #22287]  INFO -- :   Rendered layouts/_errors.html.erb (0.1ms)
I, [2018-05-01T14:32:51.824546 #22287]  INFO -- : Processing by ErrorsController#render_error as HTML
I, [2018-05-01T14:32:51.838279 #22287]  INFO -- :   Rendered errors/error_generic.html.erb within layouts/no-topmenu (1.2ms)
I, [2018-05-01T15:31:58.685206 #22287]  INFO -- :   Rendered layouts/_errors.html.erb (0.1ms)
I, [2018-05-01T15:56:13.274919 #22287]  INFO -- :   Rendered layouts/_errors.html.erb (0.1ms)
I, [2018-05-01T16:01:50.982039 #22287]  INFO -- :   Rendered layouts/_errors.html.erb (0.1ms)
I, [2018-05-01T16:01:55.315360 #22287]  INFO -- :   Rendered layouts/_errors.html.erb (0.1ms)
I, [2018-05-02T08:04:23.340551 #15685]  INFO -- :   Rendered layouts/_errors.html.erb (9.8ms)
I, [2018-05-02T08:23:33.228614 #15685]  INFO -- :   Rendered layouts/_errors.html.erb (0.1ms)
I, [2018-05-02T08:24:04.912150 #15685]  INFO -- :   Rendered layouts/_errors.html.erb (2.1ms)
I, [2018-05-02T08:24:16.199656 #15685]  INFO -- :   Rendered layouts/_errors.html.erb (0.1ms)
I, [2018-05-02T08:24:20.057872 #15685]  INFO -- :   Rendered layouts/_errors.html.erb (0.1ms)
I, [2018-05-02T08:26:07.184564 #15685]  INFO -- :   Rendered layouts/_errors.html.erb (0.0ms)

`

**Comment by mfrederickson** [comment]
This was resolved by restoring the .bundle/config and the Gemfile and Gemfile.lock from the release and restarting the server.

**Comment by joeleonjr** [comment]
Hi! I'm a security researcher @TruffleSecurity. I found a valid API key leaked in a comment in this Issue. I highly recommend rotating the API key immediately (not just deleting the comment). Here's a blog post I wrote on remediating these types of vulnerabilities: https://trufflesecurity.com/blog/remediate-leaked-api-keys-with-key-rotation.<br><br>If you can't find the leaked API key, you can use the following [TruffleHog](https://github.com/trufflesecurity/trufflehog) command to automatically scan for it:<br>`trufflehog github --repo https://github.com/<your_username>/<your_reponame> --issue-comments --only-verified`<br><br>If it's not clear where/what the security issue is, please let me know. I'd be happy to help. Please note that the API key might be in the past edit of a comment.<br><br><br><br>(cc @Millator)
