### ISSUE TITLE
Concerto 2 VM Image (.ova) broken?

### ISSUE THREAD

**Issue by jg75996** [concerto/concerto#1486]
Hello,

I am interested in trying out the virtual appliance for Concerto 2, however, of the few times that I have tried to download the image, I am unable to import it into VMware ESXi or VirtualBox.

I got errors each time.

Has anyone recently deployed the appliance successfully?

Thank you!

**Comment by adildevo** [comment]
You have to make a tar -xvf on the file with linux or cygwin when you are in Windows and then open the file .ovf extracted in VirtualBox.

**Comment by mfrederickson** [comment]
I am able to open it as is via VMWorkstation 15. I just have to reconfigure the networking.
