### ISSUE TITLE
I have problem to log in the concerto login with VM Image (.ova)

### ISSUE THREAD

**Issue by adildevo** [concerto/concerto#1487]
Hello,

I have some trouble to log in the virtual machine provided by Concerto. In fact, I am using the same id such as : "concerto" for the login and "truc9awr" for the password but it refuse the connection. Can you help me ?  I have a screenshot joined.
![problem](https://user-images.githubusercontent.com/20336218/40171387-64f198fc-59cb-11e8-8856-92dab13bdcab.PNG)

Thanks in advance

**Comment by mfrederickson** [comment]
I was able to confirm that the published credentials work on the latest vm image.
