### ISSUE TITLE
Failed install: error while trying to load the gem 'delayed_job_active_record'

### ISSUE THREAD

**Issue by briandsquinn** [concerto/concerto#1489]
*NOOB WARNING*

I've gotten an error while trying to install.  Here's the whole string:

Reading package lists... Done
Building dependency tree
Reading state information... Done
concerto-full is already the newest version (2.3.6).
0 upgraded, 0 newly installed, 0 to remove and 9 not upgraded.
1 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Do you want to continue? [Y/n] y
Setting up concerto-full (2.3.6) ...
Determining localhost credentials from /etc/mysql/debian.cnf: succeeded.
dbconfig-common: writing config to /etc/dbconfig-common/concerto-full.conf
concerto already exists and has privileges on concerto_production.
creating database concerto_production: already exists.
dbconfig-common: flushing administrative password
Successfully installed bundler-1.16.2
1 gem installed
Using rake 12.0.0
Using i18n 0.8.6
Using minitest 5.10.3
Using thread_safe 0.3.6
Using tzinfo 1.2.3
Using activesupport 4.2.9
Using builder 3.2.3
Using erubis 2.7.0
Using mini_portile2 2.2.0
Using nokogiri 1.8.0
Using rails-deprecated_sanitizer 1.0.3
Using rails-dom-testing 1.0.8
Using loofah 2.0.3
Using rails-html-sanitizer 1.0.3
Using actionview 4.2.9
Using rack 1.6.8
Using rack-test 0.6.3
Using actionpack 4.2.9
Using globalid 0.4.0
Using activejob 4.2.9
Using mime-types-data 3.2016.0521
Using mime-types 3.1
Using mail 2.6.6
Using actionmailer 4.2.9
Using activemodel 4.2.9
Using arel 6.0.4
Using activerecord 4.2.9
Using addressable 2.3.8
Using airbrake-ruby 1.8.0
Using airbrake 5.8.1
Using ansi 1.5.0
Using ast 2.3.0
Using attachable 0.0.5
Using bcrypt 3.1.11
Using thor 0.19.4
Using railties 4.2.9
Using bootstrap-datepicker-rails 1.6.4.1
Using bundler 1.16.2
Using bundler-audit 0.6.0
Using cancancan 2.0.0
Using clockwork 2.0.2
Using coffee-script-source 1.12.2
Using execjs 2.2.2
Using coffee-script 2.4.1
Using coffee-rails 4.2.2
Using multipart-post 2.0.0
Using faraday 0.9.2
Using jwt 1.5.6
Using little-plugger 1.1.4
Using multi_json 1.12.1
Using logging 2.2.2
Using memoist 0.16.0
Using os 0.9.6
Using signet 0.7.3
Using googleauth 0.5.1
Using httpclient 2.8.3
Using hurley 0.2
Using declarative 0.0.9
Using declarative-option 0.1.0
Using uber 0.1.0
Using representable 3.0.4
Using retriable 3.1.1
Using google-api-client 0.10.3
Using icalendar 2.4.1
Using hike 1.2.3
Using tilt 1.4.1
Using sprockets 2.11.3
Using sprockets-rails 2.3.3
Using rails 4.2.9
Using concerto_calendar 0.0.9
Using concerto_docsplit 0.7.5
Using concerto_frontend 0.4.3
Using concerto_hardware 0.8
Using concerto_iframe 0.1.0
Using htmlentities 4.3.4
Using iso8601 0.9.1
Using ruby-ll 2.1.2
Using oga 2.10
Using open_uri_redirections 0.2.1
Using video_info 2.5.0
Using concerto_remote_video 1.2
Using encryptor 3.0.0
Using ruby-xslt 0.9.9
Using concerto_simple_rss 1.1
Using concerto_weather 0.6
Using connection_pool 1.2.0
Using delayed_job 4.1.3
Using delayed_job_active_record 4.1.2
Using orm_adapter 0.5.0
Using responders 2.4.0
Using warden 1.2.7
Using devise 3.5.10
Using docile 1.1.5
Using ffi 1.9.18
Using rb-fsevent 0.10.2
Using rb-inotify 0.9.10
Using sass-listen 4.0.0
Using sass 3.5.1
Using font-awesome-sass 4.7.0
Using rubinius-core-api 0.0.1
Using rubinius-actor 0.0.2
Using girl_friday 0.11.2
Using google-analytics-turbolinks 0.0.5
Using i18n-js 3.0.1
Using jquery-rails 4.3.1
Using jquery-timepicker-rails 1.11.10
Using json 2.1.0
Using kaminari-core 1.0.1
Using kaminari-actionview 1.0.1
Using kaminari-activerecord 1.0.1
Using kaminari 1.0.1
Using libv8 3.16.14.19 (x86_64-linux)
Using mysql2 0.4.9
Using nprogress-rails 0.2.0.2
Using sawyer 0.6.0
Using octokit 4.2.0
Using public_activity 1.5.0
Using redcarpet 3.3.4
Using ref 2.0.0
Using rmagick 2.16.0
Using rubyzip 1.2.1
Using sass-rails 5.0.6
Using simplecov-html 0.10.2
Using simplecov 0.15.0
Using sqlite3 1.3.13
Using therubyracer 0.12.3
Using turbolinks 2.5.3
Using twitter-bootstrap-rails-confirm 1.0.6
Using uglifier 2.7.2
Bundle complete! 48 Gemfile dependencies, 129 gems now installed.
Gems in the groups postgres and development were not installed.
Bundled gems are installed into `./vendor/bundle`
rake aborted!
Bundler::GemRequireError: There was an error while trying to load the gem 'delayed_job_active_record'.
Gem Load Error is: undefined method `yaml_as' for ActiveRecord::Base:Class
Did you mean?  yaml_tag
Backtrace for gem load error is:
/usr/share/concerto/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.9/lib/active_record/dynamic_matchers.rb:26:in `method_missing'
/usr/share/concerto/vendor/bundle/ruby/2.5.0/gems/delayed_job-4.1.3/lib/delayed/serialization/active_record.rb:4:in `<class:Base>'
/usr/share/concerto/vendor/bundle/ruby/2.5.0/gems/delayed_job-4.1.3/lib/delayed/serialization/active_record.rb:3:in `<module:ActiveRecord>'
/usr/share/concerto/vendor/bundle/ruby/2.5.0/gems/delayed_job-4.1.3/lib/delayed/serialization/active_record.rb:2:in `<top (required)>'
/usr/share/concerto/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.9/lib/active_support/dependencies.rb:274:in `require'
/usr/share/concerto/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.9/lib/active_support/dependencies.rb:274:in `block in require'
/usr/share/concerto/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.9/lib/active_support/dependencies.rb:240:in `load_dependency'
/usr/share/concerto/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.9/lib/active_support/dependencies.rb:274:in `require'
/usr/share/concerto/vendor/bundle/ruby/2.5.0/gems/delayed_job-4.1.3/lib/delayed/worker.rb:66:in `backend='
/usr/share/concerto/vendor/bundle/ruby/2.5.0/gems/delayed_job_active_record-4.1.2/lib/delayed_job_active_record.rb:5:in `<top (required)>'
/var/lib/gems/2.5.0/gems/bundler-1.16.2/lib/bundler/runtime.rb:81:in `require'
/var/lib/gems/2.5.0/gems/bundler-1.16.2/lib/bundler/runtime.rb:81:in `block (2 levels) in require'
/var/lib/gems/2.5.0/gems/bundler-1.16.2/lib/bundler/runtime.rb:76:in `each'
/var/lib/gems/2.5.0/gems/bundler-1.16.2/lib/bundler/runtime.rb:76:in `block in require'
/var/lib/gems/2.5.0/gems/bundler-1.16.2/lib/bundler/runtime.rb:65:in `each'
/var/lib/gems/2.5.0/gems/bundler-1.16.2/lib/bundler/runtime.rb:65:in `require'
/var/lib/gems/2.5.0/gems/bundler-1.16.2/lib/bundler.rb:114:in `require'
/usr/share/concerto/config/application.rb:10:in `<top (required)>'
/usr/share/concerto/Rakefile:5:in `require'
/usr/share/concerto/Rakefile:5:in `<top (required)>'
/usr/share/concerto/vendor/bundle/ruby/2.5.0/gems/rake-12.0.0/lib/rake/rake_module.rb:28:in `load'
/usr/share/concerto/vendor/bundle/ruby/2.5.0/gems/rake-12.0.0/lib/rake/rake_module.rb:28:in `load_rakefile'
/usr/share/concerto/vendor/bundle/ruby/2.5.0/gems/rake-12.0.0/lib/rake/application.rb:687:in `raw_load_rakefile'
/usr/share/concerto/vendor/bundle/ruby/2.5.0/gems/rake-12.0.0/lib/rake/application.rb:96:in `block in load_rakefile'
/usr/share/concerto/vendor/bundle/ruby/2.5.0/gems/rake-12.0.0/lib/rake/application.rb:178:in `standard_exception_handling'
/usr/share/concerto/vendor/bundle/ruby/2.5.0/gems/rake-12.0.0/lib/rake/application.rb:95:in `load_rakefile'
/usr/share/concerto/vendor/bundle/ruby/2.5.0/gems/rake-12.0.0/lib/rake/application.rb:79:in `block in run'
/usr/share/concerto/vendor/bundle/ruby/2.5.0/gems/rake-12.0.0/lib/rake/application.rb:178:in `standard_exception_handling'
/usr/share/concerto/vendor/bundle/ruby/2.5.0/gems/rake-12.0.0/lib/rake/application.rb:77:in `run'
/usr/share/concerto/vendor/bundle/ruby/2.5.0/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
/usr/share/concerto/vendor/bundle/ruby/2.5.0/bin/rake:23:in `load'
/usr/share/concerto/vendor/bundle/ruby/2.5.0/bin/rake:23:in `<main>'
Bundler Error Backtrace:
/var/lib/gems/2.5.0/gems/bundler-1.16.2/lib/bundler/runtime.rb:84:in `rescue in block (2 levels) in require'
/var/lib/gems/2.5.0/gems/bundler-1.16.2/lib/bundler/runtime.rb:80:in `block (2 levels) in require'
/var/lib/gems/2.5.0/gems/bundler-1.16.2/lib/bundler/runtime.rb:76:in `each'
/var/lib/gems/2.5.0/gems/bundler-1.16.2/lib/bundler/runtime.rb:76:in `block in require'
/var/lib/gems/2.5.0/gems/bundler-1.16.2/lib/bundler/runtime.rb:65:in `each'
/var/lib/gems/2.5.0/gems/bundler-1.16.2/lib/bundler/runtime.rb:65:in `require'
/var/lib/gems/2.5.0/gems/bundler-1.16.2/lib/bundler.rb:114:in `require'
/usr/share/concerto/config/application.rb:10:in `<top (required)>'
/usr/share/concerto/Rakefile:5:in `require'
/usr/share/concerto/Rakefile:5:in `<top (required)>'
/usr/share/concerto/vendor/bundle/ruby/2.5.0/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
NoMethodError: undefined method `yaml_as' for ActiveRecord::Base:Class
Did you mean?  yaml_tag
/usr/share/concerto/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.9/lib/active_record/dynamic_matchers.rb:26:in `method_missing'
/usr/share/concerto/vendor/bundle/ruby/2.5.0/gems/delayed_job-4.1.3/lib/delayed/serialization/active_record.rb:4:in `<class:Base>'
/usr/share/concerto/vendor/bundle/ruby/2.5.0/gems/delayed_job-4.1.3/lib/delayed/serialization/active_record.rb:3:in `<module:ActiveRecord>'
/usr/share/concerto/vendor/bundle/ruby/2.5.0/gems/delayed_job-4.1.3/lib/delayed/serialization/active_record.rb:2:in `<top (required)>'
/usr/share/concerto/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.9/lib/active_support/dependencies.rb:274:in `require'
/usr/share/concerto/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.9/lib/active_support/dependencies.rb:274:in `block in require'
/usr/share/concerto/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.9/lib/active_support/dependencies.rb:240:in `load_dependency'
/usr/share/concerto/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.9/lib/active_support/dependencies.rb:274:in `require'
/usr/share/concerto/vendor/bundle/ruby/2.5.0/gems/delayed_job-4.1.3/lib/delayed/worker.rb:66:in `backend='
/usr/share/concerto/vendor/bundle/ruby/2.5.0/gems/delayed_job_active_record-4.1.2/lib/delayed_job_active_record.rb:5:in `<top (required)>'
/var/lib/gems/2.5.0/gems/bundler-1.16.2/lib/bundler/runtime.rb:81:in `require'
/var/lib/gems/2.5.0/gems/bundler-1.16.2/lib/bundler/runtime.rb:81:in `block (2 levels) in require'
/var/lib/gems/2.5.0/gems/bundler-1.16.2/lib/bundler/runtime.rb:76:in `each'
/var/lib/gems/2.5.0/gems/bundler-1.16.2/lib/bundler/runtime.rb:76:in `block in require'
/var/lib/gems/2.5.0/gems/bundler-1.16.2/lib/bundler/runtime.rb:65:in `each'
/var/lib/gems/2.5.0/gems/bundler-1.16.2/lib/bundler/runtime.rb:65:in `require'
/var/lib/gems/2.5.0/gems/bundler-1.16.2/lib/bundler.rb:114:in `require'
/usr/share/concerto/config/application.rb:10:in `<top (required)>'
/usr/share/concerto/Rakefile:5:in `require'
/usr/share/concerto/Rakefile:5:in `<top (required)>'
/usr/share/concerto/vendor/bundle/ruby/2.5.0/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
(See full trace by running task with --trace)
dpkg: error processing package concerto-full (--configure):
 installed concerto-full package post-installation script subprocess returned error exit status 1
Errors were encountered while processing:
 concerto-full
EE: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by mfrederickson** [comment]
This has been resolved via another issue and is included in release 2.3.7 (pending).
