### ISSUE TITLE
is it possible to make display computer has two monitors instead of one ?

### ISSUE THREAD

**Issue by abdelrahman146** [concerto/concerto#1492]
I'm trying to implement concreto on a project that I'm working on, and one of the requirements is the display computer should have two monitors and each monitor should represent a different signage.

please tell me if it is possible to do in concreto and how? 

Thanks,

**Comment by mfrederickson** [comment]
I suppose you could have a browser running on each monitor with each browser pointing to a different "screen" in concerto.
