### ISSUE TITLE
PDF Conversion not working

### ISSUE THREAD

**Issue by rtorrente** [concerto/concerto#1493]
PDF Conversion (imagemagik I think ?) isn't working since few days without any reason (maybe an update ?). The loading icon is visible in infinity loop.

When I look the log, when I put a PDF in file select section, I saw in the log "**Airbrake: unexpected code (200)".

Do you have any idea of the problem ?

**Comment by mfrederickson** [comment]
I had a problem similar to this when I was testing the docker image, I had to change the policy in the LibreOffice [policy.xml file.](https://stackoverflow.com/a/52661288/1778068)  If this is still an outstanding issue for you, please reopen.
