### ISSUE TITLE
Ubuntu 16.04 - apt installation - concerto/public folder no index file.

### ISSUE THREAD

**Issue by mAPBhlJ** [concerto/concerto#1497]
I've installed Concerto on Ubuntu 16.04 as per [wiki instructions](https://github.com/concerto/concerto/wiki/Installing-Concerto-2#installing-concerto-as-a-debian-package).

Everything seems to be fine as I can see the favicon when going to the webpage and also can request the robots.txt. However, it does not seem to serve me an index.html

When checking the /usr/share/concerto/public folder (using ls), I see it only has a small set of files and does not have (which would be expected) an index.html.

```
server:/usr/share/concerto/public$ ls
assets  favicon.ico  favicon_inv.png  favicon.png  images  robots.txt
```

I've also tried re-running the installation steps in the hopes it would add the missing files, but no avail:

```
apt-get install concerto-full
Reading package lists... Done
Building dependency tree       
Reading state information... Done
concerto-full is already the newest version (2.3.6).
The following packages were automatically installed and are no longer required:
  bridge-utils .......... ubuntu-fan
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 114 not upgraded.
```

**Comment by wsmith101** [comment]
Same problem here. 

Installed Ubuntu 16.04 from scratch. Run updates and installed Concerto installation.

Below some additional information. No idea if it is useful, but please let me know if you need other information.

Help is very appreciated. 


== UBUNTU VERSION ==
wsmith@concerto:/$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.5 LTS
Release:	16.04
Codename:	xenial

== APACHE VERSION ==
wsmith@concerto:/$ apache2 -v
Server version: Apache/2.4.18 (Ubuntu)
Server built:   2018-06-07T19:43:03

== CONCERTO VERSION ==
wsmith@concerto:/$ sudo apt-get install concerto-full
Reading package lists... Done
Building dependency tree       
Reading state information... Done
concerto-full is already the newest version (2.3.6).
0 upgraded, 0 newly installed, 0 to remove and 22 not upgraded.

== LIST OF index.* FILES IN usr/share/concerto ==
wsmith@concerto:usr/share/concerto$ sudo find  -type f -iname "index.*"
./vendor/bundle/ruby/2.3.0/gems/rack-1.6.8/test/cgi/assets/index.html
./vendor/bundle/ruby/2.3.0/gems/rack-1.6.8/test/static/another/index.html
./vendor/bundle/ruby/2.3.0/gems/rack-1.6.8/test/static/index.html
./vendor/bundle/ruby/2.3.0/gems/signet-0.7.3/website/index.html
./vendor/bundle/ruby/2.3.0/gems/hike-1.2.3/lib/hike/index.rb
./vendor/bundle/ruby/2.3.0/gems/erubis-2.7.0/doc-api/index.html
./vendor/bundle/ruby/2.3.0/gems/addressable-2.3.8/website/index.html
./vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.9/lib/action_dispatch/journey/visualizer/index.html.erb
./vendor/bundle/ruby/2.3.0/gems/devise-3.5.10/test/rails_app/app/views/admins/index.html.erb
./vendor/bundle/ruby/2.3.0/gems/devise-3.5.10/test/rails_app/app/views/home/index.html.erb
./vendor/bundle/ruby/2.3.0/gems/devise-3.5.10/test/rails_app/app/views/users/index.html.erb
./vendor/bundle/ruby/2.3.0/gems/httpclient-2.8.3/sample/ssl/htdocs/index.html
./vendor/bundle/ruby/2.3.0/gems/concerto_hardware-0.8/app/views/concerto_hardware/players/index.html.erb
./vendor/bundle/ruby/2.3.0/gems/json-2.1.0/data/index.html
./vendor/bundle/ruby/2.3.0/gems/sprockets-2.11.3/lib/sprockets/index.rb
./vendor/bundle/ruby/2.3.0/gems/turbolinks-2.5.3/test/index.html
./vendor/bundle/ruby/2.3.0/gems/railties-4.2.9/lib/rails/generators/erb/scaffold/templates/index.html.erb
./vendor/bundle/ruby/2.3.0/gems/railties-4.2.9/lib/rails/templates/rails/mailers/index.html.erb
./vendor/bundle/ruby/2.3.0/gems/railties-4.2.9/lib/rails/templates/rails/welcome/index.html.erb
./vendor/bundle/ruby/2.3.0/gems/rmagick-2.16.0/doc/index.html
./vendor/bundle/ruby/2.3.0/gems/girl_friday-0.11.2/server/views/index.erb
./vendor/bundle/ruby/2.3.0/gems/bootstrap-datepicker-rails-1.6.4.1/vendor/assets/javascripts/bootstrap-datepicker/index.js
./vendor/bundle/ruby/2.3.0/gems/rails-4.2.9/guides/source/index.html.erb
./app/views/concerto_plugins/index.html.erb
./app/views/fields/index.html.erb
./app/views/screens/index.html.erb
./app/views/field_configs/index.html.erb
./app/views/feeds/index.html.erb
./app/views/feeds/index.js.erb
./app/views/contents/index.html.erb
./app/views/users/index.html.erb
./app/views/submissions/index.html.erb
./app/views/submissions/index.js.erb
./app/views/groups/index.html.erb
./app/views/kinds/index.html.erb
./app/views/subscriptions/index.html.erb
./app/views/pages/index.html.erb
./app/views/templates/index.html.erb

**Comment by mfrederickson** [comment]
@Paul-Ver  that is correct that public only has those files, being a rails app, the "index" page is rendered and served dynamically.  If you are not getting anything when you browse to http://yourserver then you should check your webserver log files to see what is going on.  If you still need help then reopen this issue.
