### ISSUE TITLE
get.concerto-signage.org loads Brians world wordpress blog

### ISSUE THREAD

**Issue by felsgaertner** [concerto/concerto#1588]
The URL given in the readme.md file (https://get.concerto-signage.org) does not load a shell script, but points to a different web site.

What is the correct URL of that add_repo shell script?

**Comment by bamnet** [comment]
Oh no, I must have goofed something up in the config. I'll take a look this weekend.

**Comment by bamnet** [comment]
I moved the get.concerto-signage.org resources over to their own github repo: https://github.com/concerto/get.concerto-signage.org

It's now published using Github pages and should be working correctly, +/- DNS updates and Github's SSL provisioning.

Thanks for reporting this!
