### ISSUE TITLE
Docker image fails with date-3.3.4 not found

### ISSUE THREAD

**Issue by valheru** [concerto/concerto#1593]
When using the default docker image I get the following error:

> /usr/local/rvm/rubies/ruby-2.6.10/lib/ruby/2.6.0/bundler/spec_set.rb:91:in `block in materialize': Could not find date-3.3.4 in any of the sources (Bundler::GemNotFound)

I have tried changing the Dockerfile to install date 3.3.4 which seemed to work but did not resolve this issue.
Is there some way to get past this error?

**Comment by IsaiahCQ** [comment]
Hello, did you ever find a fix for this issue?

**Comment by bamnet** [comment]
This may have been fixed in #1595?
