### ISSUE TITLE
Support content browsing (next, back, pause) in frontend.

### ISSUE THREAD

**Issue by kench** [concerto/concerto#289]
As a screen owner, I want users to be able to browse through content on a Concerto screen (via methods such as hand gestures, touch screen interaction, or push buttons) so that they can be more engaged with content.

I have iPads functioning as a kiosk and this is a popular feature requested from users of those screens.

**Comment by augustf** [comment]
@gbprz I don't really want to deep-six this one until you've weighed in.

**Comment by gbprz** [comment]
This could work out well with Polymer's : https://elements.polymer-project.org/elements/iron-a11y-keys

**Comment by gbprz** [comment]
If it's still of interest, I'd be glad to take a look

**Comment by augustf** [comment]
Agreed. I'm still a little unclear on how general-purpose we can make something like this. v1 had some keys assigned to forward and backward which was a cool thing, but support stuff like swipes and such would seem to be somewhat proprietary to certain implementation(s). And the sort of tech that might deal with hand gestures (despite the valiant W3c efforts-https://www.w3.org/wiki/Media_Capture_Depth_Stream_Extension) would seem to be totally closed and not something we could implement in core Concerto at all.

**Comment by kench** [comment]
Still interested.  Hooks for next/back/pause would be all that's needed.  We don't need to implement support for swipes and stuff, but having the hooks exposed for those interactions would be helpful.

**Comment by augustf** [comment]
Moved to https://github.com/concerto/concerto-frontend/issues/58
