### ISSUE TITLE
Recurrent content display (by date/time/screen)

### ISSUE THREAD

**Issue by dsp103** [concerto/concerto#576]
August 10:
A feature request. Would it be possible to have content added to display "every monday" for example? Or adding content with a repeat type function?

November 13:
Here's an official feature request for Concerto 2  to be able to specify specific content, on a specific screen, at a specific time of day (with recurrence).
It would be great if we could schedule the display of daily lunch menus, special notices during morning arrival, welcome screens for parent events, etc. on specific days ayt specific times for specific durations.

**Comment by mfrederickson** [comment]
@augustf it looks like this can be closed.

**Comment by mfrederickson** [comment]
I know this is closed, but this functionality is in 
https://github.com/concerto-addons/concerto_content_scheduling
