### ISSUE TITLE
move frontend_js under assets

### ISSUE THREAD

**Issue by mfrederickson** [concerto/concerto#814]
Sprockets, according to the Gemfile.lock is now at 2.2.2, and the frontend_js directory has a readme.md that states:  

> This directory should be moved to app/assets/javascripts/frontend, but right now sprockets doesn't let us not exclude it from being bundled in the application. This is fixed in Sprockets 2.2.0, which will hopefully be in use at some point before we release Concerto 2.

**Comment by augustf** [comment]
#1078 should obsolete this.
