### ISSUE TITLE
FrontendJS should use Time fieldconfig

### ISSUE THREAD

**Issue by khanh** [concerto/concerto#921]
field.js does things differently for Time fields. This causes an inconsistency in the code that we should resolve. Now that fieldconfigs are implemented. We should use that!

**Comment by gbprz** [comment]
The frontend now takes the UTC offset provided by the screen's configured time zone into account: concerto/concerto-frontend@923b2cb672e381c6365bc91683417e3216c942f0 

The screen's UTC offset from it's configured time zone was also added to the setup.js:
#1234

**Comment by augustf** [comment]
Now that we're doing timezones on screens and the frontend is dealing with that (and DST), I think we've dealt with the essence of this ticket.
