### ISSUE TITLE
Proper use of location field

### ISSUE THREAD

**Issue by augustf** [concerto/concerto#934]
In #338, we discuss the location field briefly in the context of what is really the core use case for a screen across TV's, tablets, etc. While I'm not altogether convinced mobile devices will wind up being "screens" in most deployments, it seems reasonable to take another look at the location field.

Currently, the field is being used by most of us to semantically to refer to where the screen is ("My Room", "CII Lobby", etc). But for both TV's and mobile devices, I think this field would find better use in storing the coordinates of the screen's location. Users can pin the location on a map manually for TV's, but mobile devices could update this field on the fly as desired.

**Comment by Baylink-gh** [comment]
Would the goal be to define polygons inside which a given feed/screen is what's displayed?
