### ISSUE TITLE
PDF->PNG conversion with white background causes quality loss

### ISSUE THREAD

**Issue by augustf** [concerto/concerto#973]
As a part of the removal of the alpha channel in #947 (129e510e6b624784c8a5339bdf2ffd5b9eb30dcb), image quality from the PDF conversion has gone down. PDF conversion to PNG should be very nearly lossless.

**Comment by mfrederickson** [comment]
I just tested this and to me, it no longer looks like it is a problem.  Perhaps it was fixed in one of the tools along the way, or my eyesight isn't as good as it was.  Anyway, someone else should test this and let us know.
